### PR TITLE
Add configuration file encryption

### PR DESCRIPTION
**Pull request by klauspost**
See #317 for details.

Use `rclone config` to add/change/remove password.

### CODE REVIEW

**Comment by klauspost** [comment]
I will move forward, and write tests and documentation tomorrow.

**Comment by klauspost** [comment]
Tests and documentation added, and I squashed the commits.

I made a few adjustments to separate out easy to test functionality and make code simpler a few places. No functional changes.

I reverted the goconfig change, so it potentially could be merged upstream, and we can change back at that time.

**Comment by ncw** [comment]
Sorry Klaus for ignoring your pull requests for a while!  I wanted to get v1.27 out the door before coming back to them.  I'll get this in v1.28.

**Comment by ncw** [comment]
I gave the code thorough test and review.

It looks very good!

I found a few typos - see patch below.

Are you going to send the goconfig changes upstream? I'd rather merge with the upstream patch, but you could send a PR later.

Also I couldn't make the tests work.  The password didn't appear to work, then it tried to read it from stdin.  I don't know why the password didn't work though!

```
$ go test -v -run TestConfigLoadEncrypted
=== RUN   TestConfigLoadEncrypted
2016/02/09 23:11:52 Couldn't decrypt configuration, most likely wrong password.
Enter configuration password:
password>
2016/02/09 23:11:52 Failed to read password: inappropriate ioctl for device
exit status 1
FAIL	github.com/ncw/rclone/fs	0.004s
```


```diff
diff --git a/fs/config.go b/fs/config.go
index 1356cec..0f57628 100644
--- a/fs/config.go
+++ b/fs/config.go
@@ -378,7 +378,7 @@ func loadConfigFile() (*goconfig.ConfigFile, error) {
                        getPassword("Enter configuration password:")
                }
 
-               // Nonce is just bottom of out key
+               // Nonce is first 24 bytes of the ciphertext
                var nonce [24]byte
                copy(nonce[:], box[:24])
                var key [32]byte
@@ -392,7 +392,7 @@ func loadConfigFile() (*goconfig.ConfigFile, error) {
                }
 
                // Retry
-               log.Println("Could decrypt configuration, most likely wrong password.")
+               log.Println("Couldn't decrypt configuration, most likely wrong password.")
                configKey = nil
                envpw = ""
        }
@@ -470,7 +470,7 @@ func SaveConfig() {
        fmt.Fprintln(f, "")
        fmt.Fprintln(f, "RCLONE_ENCRYPT_V0:")
 
-       // Generate new nonce and write it
+       // Generate new nonce and write it to the start of the ciphertext
        var nonce [24]byte
        n, _ := rand.Read(nonce[:])
        if n != 24 {
```

**Comment by klauspost** [comment]
Very nice. I will look at the test first.

goconfig was positive upstream, but I haven't had the time to flesh out a full PR.

Thanks for fixing the unclear comments.

**Comment by klauspost** [comment]
The error/query was because your local configuration is encrypted, so the tests (operations_test.go) are unable to load it.

I have made it possible disable the password prompt entirely, and always fail. That may also be a help in script use.

I will see if I can rebase this, since there are conflicts now.

**Comment by klauspost** [comment]
Rebased and squashed.

If your local configuration is encrypted set `RCLONE_CONFIG_PASS=yourpassword`.

**Comment by klauspost** [comment]
Submitted https://github.com/Unknwon/goconfig/pull/31 - we will need to use the `io.Reader` interface instead of the byte slice loader, when switching back, since it writes to local disk, and I did not want to submit a PR that broke the "Reload" functionality that relies on the temporary files.

**Comment by klauspost** [comment]
Cool - `goconfig` was already merged upstream, so i will change back the import tomorrow.

**Comment by klauspost** [comment]
Import changed back and documentation updated. This should be ready for merge.

**Comment by ncw** [comment]
I've merged that - thanks Klaus - a very useful feature :-)

**Pull request merged**
