### PR TITLE
Add local file system option to disable UNC on Windows.

### LINKED ISSUE #261: rclone cannot read an encfs mounted drive on Windows 7
First mount the virtual drive using encfs

    encfs --reverse h:/folder n:

Try to perform any operation with that drive using rclone and it will return with a read error.  `dir` from the `N:\` directory works without a problem.

    N:\>rclone ls .
    2015/12/24 12:00:39 Local file system at \\?\N:\: Failed to open directory: \\?\N:\: Readdir \\?\N:\: The system cannot find the path specified.
    
    Transferred:            0 Bytes (   0.00 kByte/s)
    Errors:                 1
    Checks:                 0
    Transferred:            0
    Elapsed time:           0
    
    N:\>

I'm using Windows 7 Professional x64, encfs4win, and Dokan 0.6.0

[encfs.zip](https://github.com/ncw/rclone/files/71905/encfs.zip)

[DokanInstall_0.6.0.zip](https://github.com/ncw/rclone/files/71906/DokanInstall_0.6.0.zip)

### PR DESCRIPTION
**Pull request by klauspost**
This will add an option to disable UNC conversion on Windows to deal with buggy file system implementations like EncFS.

Fixes #261

### CODE REVIEW

**Comment by ncw** [comment]
Nice!

What do you think of adding a `--local-nounc` (or possibly `--nounc`) option as well or maybe instead of the config file changes?

**Comment by klauspost** [comment]
I did not add an option, since it will only be rarely used, and it would apply to both source and destination.

**Comment by klauspost** [comment]
Fixed the grammar, and squashed the commit.

**Comment by ncw** [comment]
I've merged this - thank you very much Klaus!

**Pull request closed without merging**
