### PR TITLE
cmd: new command lsf

### PR DESCRIPTION
**Pull request by kubatasiemski**
Please find information in my comment in issue #1157.

### CODE REVIEW

**Comment by ncw** [comment]
Thanks for doing this. I think it is a good idea!

I'd like the default output to be the same as `rclone ls2` - then I can retire that (hidden command).

Can you also write some unit tests for the formatting please?  We are going to commit to keeping the output of this command stable, so it is important we have tests.  Let me know if you need help with them.

**Comment by kubatasiemski** [comment]
> I'd like the default output to be the same as rclone ls2 - then I can retire that (hidden command).
Ok, great idea 💡!

> Can you also write some unit tests for the formatting please? We are going to commit to keeping the output of this command stable, so it is important we have tests. Let me know if you need help with them.
Thanks, I think it will be easy. I will do that at the beginning of the next week :)

**Comment by kubatasiemski** [comment]
@ncw Could you look on error in Travis CI? 
>oci runtime error: exec failed: container_linux.go:265: starting container process caused "could not create session key: disk quota exceeded"

I tkink this is not my fault. If you can fix that, could you also rerun lsf build?

**Comment by ncw** [comment]
That is looking great - thank you :-)

I'm going to merge this now.  I will write a few more docs for the command in a moment.

Thanks :-)

**Pull request merged**
