### PR TITLE
Read folders in separate goroutines.

### PR DESCRIPTION
**Pull request by klauspost**
As proposed in the FIXME, read folders in parallel.
This appears to fix "Next token is expired" on very big directories.
The only downside is that this doesn't abort at once if an error is found.
I added some logging, so there is some output for "-v".

### CODE REVIEW

**Comment by ncw** [comment]
Nice! 

I have a slight concern about the potentially unlimited concurrency. However the pacer will ensure that we don't abuse the server so the worst case is equivalent to loading the directory tree into memory all at once which isn't a big concern. 

Drive could do with this fix too - it has the same pattern in it. 

It makes sense it fixes the next token expired and that is probably a good reason for putting it in drive too.

**Comment by ncw** [comment]
Having thought a bit more about it, I think this can break the guarantee that rclone tries to provide of not doing more than `fs.Config.Checkers` operations simultaneously with the server.  Eg if directory listings are taking 1s say, but we are launching a new one every 10mS via the pacer.

I suggest you re-organise this into `fs.Config.Checker`s worker goroutines, a channel (which probably takes a struct) to feed them data. This channel wants to be made big (say 1000 entries) so that the top level directory can run through to the end without stopping to avoid the expired next token.

This then gives the ability to stop everything when an error is detected by closing the feeding channel also which is a bonus.  You'll note that I want List and ListDir to return errors at some point in #127

You can see this pattern in use in fs/operations.go if you want some inspiration!

Thanks

Nick

**Comment by klauspost** [comment]
Ok. However, it seems like there is already some limiting going on. There are never more than 4-6 connections  "in flight" with this code. If I limit it to no more than 8 connections it doesn't seem to have any effect. Are you sure it isn't limited somewhere else?

I am testing on a directory structure with 41276 files in 4321 directories, so differences should be visible. Without the change it takes (>30 minutes) at which point it just errors out. With this change it takes ~14 minutes to list all files.

**Comment by ncw** [comment]
Try reducing the minimum time for the pacer. I set it to 100ms which is probably too high. It is a trade off between getting steady throughput and having to retry. Drive uses 10ms

**Comment by klauspost** [comment]
Ah - that could be why it seems to be limited. Lowering the minSleep to 20ms there are more concurrent connections. With maximum of 8 connections the directory listing completes in **4 minutes** with only a few "500 Internal Server error".

Maybe pacer values that are
```Go
	minSleep           = 20 * time.Millisecond
	maxSleep           = 15 * time.Second
```

I went for a slightly simpler approach with a channel with a number of "tokens".

**Comment by ncw** [comment]
Thanks for that - excellent work :-)

I've merged it now.

I think the min and max delay need a bit more thought - I'll experiment, but your values are fine for the moment.

I thought about the token approach you took but I thought the other way would control the errors better.  Anyway what you did is fine and we'll revisit in #127

**Pull request closed without merging**
