### PR TITLE
Comply with XDG Base Directory specification

### LINKED ISSUE #868: support XDG_CONFIG_HOME
I would be great to have rclone use $XDG_DATA_HOME/rclone/config, and then $HOME/.rclone.conf as a fallback.

### PR DESCRIPTION
**Pull request by kynikos**
Disclaimer: I haven't tested this patch, and I have very little experience with Go.

Fixes #868

### CODE REVIEW

**Comment by kynikos** [comment]
Travis CI complains about `fs/config.go:220:14: os.MkdirAll(xdgcfgdir, os.ModePerm)`, but I adapted the code from http://stackoverflow.com/a/37932672/645498

**Comment by ncw** [comment]
I'm sorry, I thought I replied to this, but I must have forgotten to press submit or something :-(

Travis is complaining about you not checking the error from `os.MkdirAll`

The patch itself looks OK, but I'm concerned about backwards compatibility - I don't want rclone to stop working for people with their config in the old place.

**Comment by kynikos** [comment]
Thanks, I've rewritten the patch to be backwards compatible, i.e. it uses ~/.rclone.conf if it already exists, otherwise it looks for ~/.config/rclone/rclone.conf or creates it if it doesn't exist.
I think I've properly checked the error from `os.MkdirAll`, but `make check` is failing now? Can you spot what is wrong in the code?

**Comment by ncw** [comment]
>Thanks, I've rewritten the patch to be backwards compatible, i.e. it uses ~/.rclone.conf if it already exists, otherwise it looks for ~/.config/rclone/rclone.conf or creates it if it doesn't exist.

Looks good :-)

> I think I've properly checked the error from os.MkdirAll

I'd have probably done a `log.Fatalf("Failed to make config directory %q: %v",xdgcfgdir, err )` if the `os.MkdirAll` failed rather than carry on.

> but make check is failing now? Can you spot what is wrong in the code?

make check is complaining that you haven't run `go fmt` on your code.

I get my editor to run that on a save hook.  (Actually I use goimports which writes the imports lines, but same idea).

----

Here is a thought I had in the reply I forgot to send that I just remembered

In [the XDG spec](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) it says

> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

So maybe it should be defaulting to `$HOME/.config` even if the variable isn't set?  This answer [on superuser.com agrees](http://superuser.com/a/425712/97813)

On my ubuntu laptop I have lots of XDG vars but not XDG_CONFIG_HOME, but I do have a .config with lots of stuff in it.

Thoughts?

```
$ env | grep XDG
XDG_VTNR=7
XDG_SESSION_ID=c2
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/ncw
XDG_MENU_PREFIX=xfce-
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_CONFIG_DIRS=/etc/xdg/xdg-xubuntu:/usr/share/upstart/xdg:/etc/xdg:/etc/xdg
XDG_SESSION_TYPE=x11
XDG_SEAT=seat0
XDG_SESSION_DESKTOP=xubuntu
XDG_DATA_DIRS=/usr/share/xubuntu:/usr/share/xfce4:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop:/usr/share
XDG_RUNTIME_DIR=/run/user/502
XDG_CURRENT_DESKTOP=XFCE
```

**Comment by kynikos** [comment]
I've made some more changes, I agree with defaulting to defaulting to `$HOME/.config`.
I'm only wondering if it's consistent to exit with `log.Fatalf` if `os.MkdirAll` fails, when the default behavior of the program in all the other cases (also before these patches) is to use a `.rclone.conf` file in the current directory.
Then I can't make the tests pass on AppVeyor (Windows): I've tried with 3 additional patches, but to no avail... :( Especially I was very confident that test3 would pass, even though it wouldn't have been a definitive solution, but no way... Maybe you have more experience and can tell what's wrong?

**Comment by ncw** [comment]
> I've made some more changes, I agree with defaulting to $HOME/.config.

Great

> I'm only wondering if it's consistent to exit with log.Fatalf if os.MkdirAll fails, when the default behavior of the program in all the other cases (also before these patches) is to use a .rclone.conf file in the current directory.

I'm happy to go with what you suggest.

> Then I can't make the tests pass on AppVeyor (Windows): I've tried with 3 additional patches, but to no avail... :( Especially I was very confident that test3 would pass, even though it wouldn't have been a definitive solution, but no way... Maybe you have more experience and can tell what's wrong?

Looks like I broke the Windows build :-(  WIll fix shortly - then you'll need to rebase and force push.

**Comment by ncw** [comment]
I've fixed the windows build in 9fdeb823282e5b6af943b62a644af932c0bcc7ba - really sorry about that!

**Comment by kynikos** [comment]
No worries, thanks for the fix, but now are the Travis/Linux builds that fail with "An error occurred while generating the build script", is it still something on your end?

Meanwhile I've changed the patch again, now the code is clearer, and it first checks for an existing `.config/rclone/rclone.conf`, then for an existing `~/.rclone.conf`, then it tries to create them in the same order. This should still be backwards compatible, but more compliant with the XDG specification.

I've decided to remove the `log.Fatalf` line, I do think the behaviour is more consistent without it.

Finally, I've added a patch to use `filepath.Join` instead of `path.Join`, because when trying to debug the Windows build I noticed that it uses the proper OS path separator.

**Comment by ncw** [comment]
> No worries, thanks for the fix, but now are the Travis/Linux builds that fail with "An error occurred while generating the build script", is it still something on your end?

Travis end I think.  I restarted those builds - will check back in a bit...

**Comment by kynikos** [comment]
Yay, they passed! If you're happy with the patches, I don't have anything more to add and you can merge them, cheers
In the ArchWiki we keep a [list of applications' compliance with the XDG standard](https://wiki.archlinux.org/index.php/XDG_Base_Directory_support), I'll try to remember to update it when the next version of rclone is released, but if I don't, this post will perhaps remind somebody else.

**Comment by ncw** [comment]
I've tested that and merged it thank you very much!

I updated the docs to reflect that we use `.config/rclone/rclone.conf` even if `XDG_CONFIG_HOME` isn't set - I think that must have been from a previous revision.

I'm glad you've done this - I keep being nagged by a colleague at work about this (Arch user also) and this will make him very happy!

Thanks

Nick

**Pull request closed without merging**
