### PR TITLE
Add IAM role and Env credentials

### PR DESCRIPTION
**Pull request by stengaard**
This will make the s3 provider do authentication as

  - Configured credentials (if available)
  - AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY environment variables
  - IAM role credentials (adds 1s timeout for resolving credentials)
  - No credentials (anonymous access)

### CODE REVIEW

**Comment by ncw** [comment]
That looks very useful thank you.

Would you mind adding a bit to the docs: docs/content/s3.md explaining the above and how you configure rclone to use the IAM roles credentials.

Thanks

Nick

**Comment by stengaard** [comment]
I can add the docs, no problem. But you shouldn't need to set it up. 

If the environment variables are there it'll use those.

If there's an EC2 metadata server running that responds with a set of credentials from `http://169.254.169.254/latest/meta-data/iam/security-credentials/<role-name>/` it will pick up and use those. 

Note: that this'll add a 1sec delay to the anonymous s3 use case, since we have to wait for the ec2 metadata request to time out. I am not sure how common that use case is. Alternatively we could add configuration that only does IAM roles if enabled. But I do like that it works without a lot of setup and config.

**Comment by ncw** [comment]
I'm not sure I really like the 1 second pause - what if the server is down for some reason then it will fallback to anonymous which probably isn't what you want.

I wonder whether we should change the anonymous access so it requires the `access_key_id` of `anonymous`. Your sequence of fallbacks if the credentials are empty would make more sense then
  * AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY environment variables
  * IAM role credentials
  * An error if both of those fail

I note that the text in the configurator wording needs to change too

```go
		Options: []fs.Option{{
			Name: "access_key_id",
			Help: "AWS Access Key ID - leave blank for anonymous access.",
		}, {
			Name: "secret_access_key",
			Help: "AWS Secret Access Key (password) - leave blank for anonymous access.",
		}, {
```

**Comment by stengaard** [comment]
Won't `access_key_id = "anonymous"` be a significant change of the config interface? (As in people migrating to the new version will have to fix their config.) Are we cool with that?

**Comment by ncw** [comment]
On second thoughts I think you are right `access_key_id = "anonymous"` is probably not a good idea.

What do you think of having something like this in the configurator?

```
Select authentication type
1) access_key_id / secret_access_key - use this if not sure
2) anonymous access
3) use environment variables AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY 
4) use IAM role credentials (for within EC2 only)
```

Then change something like this

```
		Options: []fs.Option{{
			Name: "access_key_id",
			Help: "AWS Access Key ID - leave blank for anonymous access, env var or IAM",
		}, {
			Name: "secret_access_key",
			Help: "AWS Secret Access Key (password) - leave blank for anonymous access, env var or IAM.",
		}, {
```

So we could be explicit about exactly which options we are supporting.  Would that be useful to you?

**Comment by stengaard** [comment]
How do you feel about what I just pushed?

**Comment by ncw** [comment]
I made a few comments on the PR, but I think it is basically good - I like the concept of auth in the config file OR from the environment with the auto choices - nice one!

**Comment by ncw** [comment]
Can you update, rebase, squash and update the PR and I'll merge.

Thanks

Nick

**Comment by stengaard** [comment]
Sure - I'll get on that. :)

**Comment by ncw** [comment]
That is looking really good.

I've merged and pushed to a branch `stengaard-iam-role-credentials`

While testing, I realised that auth from env vars doesn't seem to work.  I made a fix here ce4c1d4f356776e238b5ce367c42f0a40f680855

If you are happy that that fix does the right thing then I'll merge to master.

I also patched the docs here a0b9bd527ea0b6ea1e48392b87f56f26ab919e35

**Comment by stengaard** [comment]
Looks brilliant! Sorry for missing this.

**Comment by ncw** [comment]
I've merged this now.  Thank you very much for your contribution :-)

**Pull request closed without merging**
