### PR TITLE
fs/check: Add total matching files stats message

### PR DESCRIPTION
**Pull request by TioBorracho**
#### What is the purpose of this change?
Add an additional information message to check command to add the total matching files count

#### Was the change discussed in an issue or in the forum before?
No, AFAIK

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [X] I have added tests for all changes in this PR if appropriate.
- [X] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
Sorry for the delay in replying!  The goal seems worthy but I don't really like the approach of parsing our own log files - can you have a go at adding counters?

**Comment by TioBorracho** [comment]
will have a go at that.

**Comment by TioBorracho** [comment]
PTAL

**Comment by ncw** [comment]
Apologies for the delay.  That looks great now - thank you - will merge :-)

**Pull request merged**
