### PR TITLE
Refactor List/ListDir

### PR DESCRIPTION
**Pull request by klauspost**
WIP: DO NOT MERGE. Tests are expected to fail.

Concept proposal for #316

This shows the concept. All the heavy lifting is done in the "fs" package, making file system implementations a bit simpler.

/fs shows interfaces, and should compile.
/amazonclouddrive: Changed to new interface.
/b2: Changed to new interface.
/local: Changed to new interface.

The Fs no longer needs to create a separate goroutine when List/ListDir is called. Instead it can block as long as it likes. This simplifies implementations a bit (at least it doesn't become more complex).

Implementation is hidden in "fs" package, and only exposes the minimally needed interface, which of course can be extended.

### CODE REVIEW

**Comment by klauspost** [comment]
The only thing I don't particularly like is that `func (o *listOpts) Get() (Object, error)` returns `nil, nil` to indicate that there are no more objects. However, `func (o *listOpts) Get() (Object, bool, error)` seems clunky. 
Furthermore `Get()` is only used internally in "fs", so it isn't a "public" issue.

**Comment by ncw** [comment]
It looks like a good idea - well done!

I'm not particularly worried about the use of the `nil` Object in `Get` as a sentinel.

There are clearly some bits which need reworking a bit after this (eg the fatal errors should be returned up the layers).

Looking at the duplicated code between listdir and list it makes me think that combining the two might be the thing to do.  There are issues like #213 and #100 which would be improved if rclone knew a bit more about directories.  This would mean more options in listOpts to only list directories or files or both, and a way of passing the directories back - maybe as a different sort of Object.

This would be easy for fses like ACD - a little harder for ones like s3/swift but a with a helper function it would be straight forward.

**Comment by ncw** [comment]
Here is another issue which could be helped by a bit better directory / file integration #268

**Comment by klauspost** [comment]
Great idea to merge the interfaces. Makes it much cleaner, and avoids the duplication. 

This change means that List both returns directories and objects, but the receiver can chose to ignore one or the other. 

The only complication I found was directory size calculation ([see this](https://github.com/ncw/rclone/commit/f17ae5fd54de80f3c0ef86d15fd6e2c45b5f77bd#commitcomment-16146009)), which becomes a bit tricky. Since `filepath.Walk` has no way easy way of keeping track of which directories a file belongs to.

Right now, it should return all (sub)-directories, not just the root.

**Comment by ncw** [comment]
Originally rclone only supported swift, and swift can tell you how many files and directories are in a bucket which is where the feature came from originally. There is sporadic support amongst the the other remotes for parts of it.  So dropping that from the local fs is no big deal! `rclone size` works very well for finding out stuff like that now too.

I rebased the branch (which was a little tricky!) and pushed it to the `list-refactor` branch which I propose we keep as a long running branch.

A couple of things I noticed while doing that

  * `newListOpts` will need to be public as fs.List is a public interface
  * Having a ListOpts.GetObject and .GetDir would simplify the code a bit - these would just call .Get until they got the right kind of object.
  * We'll have to add a depth parameter to ListOpts so `lsd` can work as it does now - this will be good for other things too.

I'll take a stab at adding support to some of the other remotes and see what that looks like.

**Comment by klauspost** [comment]
Sounds like a good plan.

>Having a ListOpts.GetObject and .GetDir would simplify the code a bit - these would just call .Get until they got the right kind of object.

That could be tricky, since a full channel could block further processing. The intention behind the current design was that you would only need one consumer goroutine. If you separate Get into two functions, you would either need two goroutines, or it should return without blocking, which is also suboptimal.

**Comment by ncw** [comment]
I meant something like this (untested) which I think satisfies the requirements.

```go
// GetObject gets an object from the listing, skipping over
// directories.  Returns nil, nil at the end of the listing.
func (o *listOpts) GetObject() (Object, error) {
	for {
		o, dir, err := opts.Get()
		if err != nil {
			return nil, err
		}
		// Check if we are finished
		if dir == nil && o == nil {
			return nil, nil
		}
		// Ignore directories
		if dir == nil {
			return o, nil
		}
	}
}

// GetDir gets a Dir from the listing, skipping over Objects.  Returns
// nil, nil at the end of the listing.
func (o *listOpts) GetDir() (*Dir, error) {
	for {
		o, dir, err := opts.Get()
		if err != nil {
			return nil, err
		}
		// Check if we are finished
		if dir == nil && o == nil {
			return nil, nil
		}
		// Ignore objects
		if o == nil {
			return dir, nil
		}
	}
}
```

**Comment by klauspost** [comment]
Ah - I see. I didn't get the "skip the other type" part. Of course. I see how that makes implementations easier!

If there is more I can do here, just let me know, or open a PR with the new branch, if you would like feedback before merge.

**Comment by ncw** [comment]
I'm closing this one in favour of #446

**Pull request closed without merging**
