### PR TITLE
Always use UNC (long) paths on Windows.

### LINKED ISSUE #124: windows, local: errors from path.Rel
A local copy caused [filepath.Rel](http://golang.org/pkg/path/filepath/#Rel) to give an error

    rclone copy y:\ dir\

``` 
2015/09/06 17:54:01 Local file system at y:: Failed to get relative path y:\path\to\file.pdf: Rel: can't make \path\to\file.pdf relative to 2015/09/06 17:54:01 Local file system at dir: Waiting for
```

Fix by making the path absolute?

### PR DESCRIPTION
**Pull request by klauspost**
EDIT: Can be merged (after review)

Paths in local file systems are now all absolute. 

Changing "\" to "/" prior to that makes "C:\" change to "C:/", which is incorrectly interpreted as *current directory* by `filepath.Abs()`, so we cannot use `filepath.toSlash()` before we make the path absolute.

Fixes #124 

TO REVIEW: `filepath.ToSlash()` is removed for ALL filesystems, so they will be served the raw path. This means that "ACD:\filedir\" is no longer changed to "ACD:/filedir/", but that should be handled by each FS, if we keep it as is.

### CODE REVIEW

**Comment by ncw** [comment]
I think this looks like a sensible approach.  The previous attempt looks like an mistake.

I don't think this will regress #37

**Comment by ncw** [comment]
I'm having second thoughts about removing the `ToSlash` for all file systems.  Windows users quite often type `rclone copy C:\path\to\dir drive:\path\to\dir` and expect it to work.

**Comment by klauspost** [comment]
Added some WIP stuff. Not working yet, so do not merge!

**Comment by klauspost** [comment]
This PR fixes #130:
```
c:\GoPath\src\github.com\ncw\rclone>rclone copy \\KLAUS-LAPTOP\Users\Post\redis c:\temp\redis
2015/09/14 14:29:20 Local file system at \\?\c:\temp\redis: Building file list
2015/09/14 14:29:20 Local file system at \\?\c:\temp\redis: Waiting for checks to finish
2015/09/14 14:29:20 Local file system at \\?\c:\temp\redis: Waiting for transfers to finish

Transferred:        90993 Bytes (1614.61 kByte/s)
Errors:                 0
Checks:                 0
Transferred:           18
Elapsed time:  55.0353ms
```

**Comment by klauspost** [comment]
This should now be ready for review. I changed the code to always use UNC paths on Windows, so we don't run into "path too long" errors.

I also added cleaning of reserved Windows file path+file characters, replacing them with "_", and modified the tests to also look for these.

I tried to be careful not to modify anything non-Windows, but it would be a good idea to run tests on at least one system.

**Comment by klauspost** [comment]
Fixes #90:
```
c:\GoPath\src\github.com\ncw\rclone>rclone copy \\KLAUS-LAPTOP\Users\Post\redis c:\temp\redis\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd\sdfsdfsdfsdfd2\

[...]

Transferred:        90993 Bytes (1812.31 kByte/s)
Errors:                 0
Checks:                 0
Transferred:           18
Elapsed time:  49.0316ms
```

**Comment by ncw** [comment]
I've merged that in f50f353b5d7e76d8f666ac1383f5c23021b6ea34

Thank you for an excellent bit of work.

I've tested it (with the full test suite) under linux and it works fine there too.

**Pull request closed without merging**
