### PR TITLE
Added support for Online.net C14

### PR DESCRIPTION
**Pull request by abhimadhani**

### CODE REVIEW

**Comment by abhimadhani** [comment]
I am new to this technique of making changes to someone else's repository. So as it should it be, 

1. Github created a fork in my account of rclone, 
2. I made the changes to the README.md file
3. Made a pull request to ncw:rclone from my repository
4. It shows "This branch has no conflicts with the base branch"
5. Unsure as what does "2 pending checks means"

Do they need to be cleared to successfully make a pull request, if so can someone point how can this be done ?

**Comment by ncw** [comment]
You could add this to the homepage too if you want: https://github.com/ncw/rclone/blob/master/docs/content/about.md

With a link to the sftp docs and the C14 docs.

**Comment by ncw** [comment]
Sorry for the delay in responding.

My preference would be to add a paragraph to the sftp docs about c14 with that link in it then link the home page to that.

**Comment by ncw** [comment]
Shall I merge this as-is or do you want to add more to it?

Thanks

**Comment by ncw** [comment]
The service works perfectly with rclone's SFTP support.  This PR is about documenting that a bit better!

**Comment by HazCod** [comment]
@ncw can we merge this?

**Comment by ncw** [comment]
@HazCod this PR is about the docs only.  C14 is fully supported via the SFTP backend.

**Comment by ncw** [comment]
I'd really like this to be the complete solution which would be adding text/links to
- README.md - main GitHub page
- docs/content/sftp.md - add a paragraph about C14
- docs/content/about.md - front page of rclone.org, add a link to C14 home page and a link to the paragraph on C14

I'm going to close this PR, but if you'd like to do the above then please open a new one - thanks

**Pull request closed without merging**
