### PR TITLE
WIP: Automatic docs generation via Netlify

### PR DESCRIPTION
**Pull request by darthShadow**
#### What is the purpose of this change?

This PR is to auto-generate the docs after every commit, PR etc. via [Netlify](https://netlify.com). Makes it much easier to review any docs changes.

@ncw Let me know if this is useful and whether you would be interested in merging it. I have already been trying it out on my private fork and it seems to work fine.

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by darthShadow** [comment]
Yeah, sorry, just wanted to check interest before adding the config file etc.

I think I didn't explain it properly. Netlify is basically a CI/CD tool like Travis or Appveyor for documentation. It will generate documentation on every commit for every monitored branch and for every pull request and host it at its own URL (separate for every commit/PR). This seemed interesting to me since this will simplify the process of any doc fixes if everyone can simply check their changes live immediately.

**Comment by ncw** [comment]
Sorry for the delay in responding...

Can I look at the netlify.toml?  Have you a link to it in your repo?

I think in principle this is a nice idea, but I'd like to see it in action - have you got any more info or links?

**Comment by darthShadow** [comment]
I will try to commit a very basic `netlify.toml` within a few days. I haven't actually tried out the configuration file myself. Always used the UI @ [Netlify](https://www.netlify.com) for configuration till now.

**Comment by ncw** [comment]
I'm going to close this as we haven't made any progress for a while and I'm trying to tidy up old pull requests.  Please continue in a new pull request if you would like.

Thanks

**Pull request closed without merging**
