### PR TITLE
Update drive.md

### PR DESCRIPTION
**Pull request by animosity22**
Fixed the Google Drive API documentation

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
Thank you for that :-)

Do you think that I should change the default pacer for drive?  At the moment it allows 100 transactions per second - I could easily change that to 10 per second.

**Comment by animosity22** [comment]
@ncw  -  I think that would make sense if the quota defaults for a new API are 1000 per 100 seconds, it seems that 10 would be a much better number. I'm not sure what the rclone key itself is.

**Comment by ncw** [comment]
@animosity22 I've been running a little experiment on this. It looks like for uploading files 10 tps is exactly the right limit for your own key.

image

This is what the rclone key looks like.  It has an overall limit of 1200 QPS and a max/user/100s of 1000 just like a standard key

image

So I think setting the pacer to 10 transactions per second by default for drive would make very little difference in throughput but should reduce the likelihood of a ban enormously.

It should help with the enormous error rate in the rclone key too!

I wonder whether the pacer minimum time should be configurable?

**Comment by ncw** [comment]
I turned the pacer discussion into a new issue #2880

**Pull request merged**
