### PR TITLE
Record names coming from Dropbox API, fixes #53

### LINKED ISSUE #53: dropbox: case insensitivity causes duplicated files
I'm trying to sync Dropbox to my local machine (Linux) with rclone -v -n sync dropbox:/ ~/data

```
$ rclone -v -n sync dropbox:/ ~/data 2>&1 | grep -i Console2
2015/05/03 22:48:14 tools/Console2/Console.exe: Not copying as --dry-run       
2015/05/03 22:48:14 tools/Console2/console.chm: Not copying as --dry-run       
2015/05/03 22:48:14 tools/Console2/FreeImage.dll: Not copying as --dry-run     
2015/05/03 22:48:14 tools/Console2/ConsoleHook.dll: Not copying as --dry-run   
2015/05/03 22:48:14 tools/Console2/FreeImagePlus.dll: Not copying as --dry-run 
2015/05/03 22:48:14 tools/Console2/console.xml: Not copying as --dry-run       
2015/05/03 22:48:28 Tools/Console2/console.chm: Not deleting as --dry-run      
2015/05/03 22:48:29 Tools/Console2/ConsoleHook.dll: Not deleting as --dry-run  
2015/05/03 22:48:29 Tools/Console2/FreeImagePlus.dll: Not deleting as --dry-run
2015/05/03 22:48:29 Tools/Console2/FreeImage.dll: Not deleting as --dry-run    
2015/05/03 22:48:29 Tools/Console2/console.xml: Not deleting as --dry-run      
2015/05/03 22:48:29 Tools/Console2/Console.exe: Not deleting as --dry-run      
```
while
```
$ rclone lsd dropbox:/
[...]
           0 0001-01-01 00:00:00        -1 Tools
[...]

$ rclone lsd dropbox:/Tools
[...]
           0 0001-01-01 00:00:00        -1 Console2
[...]

$ ls -la ~/data
[...]
drwxrwxrwx 18 dropboxbackup dropboxbackup       19 May  1 17:57 Tools
[...]
```

Looks like some case problem.

Thank you!

### PR DESCRIPTION
**Pull request by shalupov**
I fixed #53 
I'll be happy to fix any issues with this pull request

### CODE REVIEW

**Comment by ncw** [comment]
Fantastic contribution - thank you!

Here are a few things I've noticed.  Can you fix and update the pull request?

Thank you very much

Nick

dropbox tests
------------------

I couldn't get the tests to pass.

```
--- FAIL: TestFsListRoot (13.65s)
	fstests.go:225: Didn't find "sw8qmkqzec0dgwtgehdsmh4mev4z38pc/file name.txt" (false) and "sw8qmkqzec0dgwtgehdsmh4mev4z38pc/hello? sausage/êé/Hello, 世界/ \" ' @ < > & ?/z.txt" (false) or no files (count 1289)
=== RUN TestFsListFile1
2015/05/18 20:16:26 Not found "file name.txt"
2015/05/18 20:16:26 Not found "hello? sausage/êé/Hello, 世界/ \" ' @ < > & ?/z.txt"
--- FAIL: TestFsListFile1 (1.40s)
	fstest.go:96: 2 objects not found
=== RUN TestFsNewFsObject
--- PASS: TestFsNewFsObject (43.32s)
=== RUN TestFsListFile1and2
2015/05/18 20:17:17 Not found "file name.txt"
2015/05/18 20:17:17 Not found "hello? sausage/êé/Hello, 世界/ \" ' @ < > & ?/z.txt"
--- FAIL: TestFsListFile1and2 (7.49s)
	fstest.go:96: 2 objects not found
```

To run the tests against Dropbox you need to make a remote called `TestDropbox`, then run `go test -v` in the dropbox directory.

You should also be able to run `make test` from the top level directory

```
[TestDropbox]
type = dropbox
app_key = 
app_secret = 
token = secretstuff
```

travis tests
--------------

The travis tests failed because of your use of "github.com/stretchr/testify/assert".  This can be fixed by adding `-t` to the `go get` line in the `.travis.conf`

misc
------

There is a typo a few times in `nametree.go` - `CaseInsensetive`

**Comment by shalupov** [comment]
Thank you! I'll fix it.

Also, please fix 
googlecloudstorage/googlecloudstorage.go:45: undefined: storage.DevstorageFull_controlScope 

I've seen it locally and in https://travis-ci.org/ncw/rclone/jobs/63057486

**Comment by shalupov** [comment]
Ok, looks like it won't be that easy. Directory entry may come after file entry from that directory:

Example:
"""
2015/05/19 02:19:20 Dropbox root '': deltaEntry: path: "/kxsyaejsa7r1wlokesm06giy7gea2eg2/file name.txt" IsDir: %!q(bool=false)
2015/05/19 02:19:20 Dropbox root '': deltaEntry: path: "/kxsyaejsa7r1wlokesm06giy7gea2eg2" IsDir: %!q(bool=true)
2015/05/19 02:19:20 Dropbox root '': deltaEntry: path: "/kxsyaejsa7r1wlokesm06giy7gea2eg2/hello? sausage/êé/Hello, 世界/ \" '
@ < > & ?/z.txt" IsDir: %!q(bool=false)
2015/05/19 02:19:20 Dropbox root '': deltaEntry: path: "/kxsyaejsa7r1wlokesm06giy7gea2eg2/hello? sausage" IsDir: %!q(bool=true)
"""

That's why tests are failing. And I've successfully tested it manually on my real dropbox before...

**Comment by ncw** [comment]
I've fixed "googlecloudstorage/googlecloudstorage.go:45: undefined: storage.DevstorageFull_controlScope" - it was a breaking API change in the google cloud storage library which I hadn't updated locally yet.

You should be able to fix your problem by splitting the loop into two and scanning for directories first?

**Comment by shalupov** [comment]
Ok, that's the new version. I've tested it with TestDropbox remote

**Comment by ncw** [comment]
Sorry I've been away!  I'll try to review this at the weekend.

Thanks

Nick

**Comment by ncw** [comment]
The unit tests for the dropbox module work fine

```
cd $GOPATH/src/github.com/ncw/rclone/dropbox
go test -v
```

But unfortunately the integration tests fail :-(  I run these as part of doing a release (via the `test_all.sh` script).

```
cd $GOPATH/src/github.com/ncw/rclone/fs
go test -v --remote TestDropbox: --subdir
```

Any ideas?

Thanks

Nick

**Comment by shalupov** [comment]
I've run tests again, they are ok. Please show your log.

...github.com/ncw/rclone/dropbox$ go test -v
=== RUN TestInit
--- PASS: TestInit (2.32 seconds)
=== RUN TestFsString
--- PASS: TestFsString (0.00 seconds)
=== RUN TestFsRmdirEmpty
--- PASS: TestFsRmdirEmpty (1.05 seconds)
=== RUN TestFsRmdirNotFound
--- PASS: TestFsRmdirNotFound (0.80 seconds)
=== RUN TestFsMkdir
--- PASS: TestFsMkdir (1.13 seconds)
=== RUN TestFsListEmpty
--- PASS: TestFsListEmpty (0.28 seconds)
=== RUN TestFsListDirEmpty
--- PASS: TestFsListDirEmpty (0.35 seconds)
=== RUN TestFsNewFsObjectNotFound
--- PASS: TestFsNewFsObjectNotFound (0.26 seconds)
=== RUN TestFsPutFile1
--- PASS: TestFsPutFile1 (3.12 seconds)
=== RUN TestFsPutFile2
--- PASS: TestFsPutFile2 (3.19 seconds)
=== RUN TestFsListDirFile2
--- PASS: TestFsListDirFile2 (0.26 seconds)
=== RUN TestFsListDirRoot
--- PASS: TestFsListDirRoot (0.53 seconds)
=== RUN TestFsListRoot
--- PASS: TestFsListRoot (0.89 seconds)
=== RUN TestFsListFile1
--- PASS: TestFsListFile1 (0.30 seconds)
=== RUN TestFsNewFsObject
--- PASS: TestFsNewFsObject (0.27 seconds)
=== RUN TestFsListFile1and2
--- PASS: TestFsListFile1and2 (0.28 seconds)
=== RUN TestFsRmdirFull
--- PASS: TestFsRmdirFull (0.27 seconds)
=== RUN TestFsPrecision
--- PASS: TestFsPrecision (0.00 seconds)
=== RUN TestObjectString
--- PASS: TestObjectString (0.26 seconds)
=== RUN TestObjectFs
--- PASS: TestObjectFs (0.31 seconds)
=== RUN TestObjectRemote
--- PASS: TestObjectRemote (0.26 seconds)
=== RUN TestObjectMd5sum
--- PASS: TestObjectMd5sum (0.27 seconds)
=== RUN TestObjectModTime
--- PASS: TestObjectModTime (0.27 seconds)
=== RUN TestObjectSetModTime
--- PASS: TestObjectSetModTime (0.93 seconds)
=== RUN TestObjectSize
--- PASS: TestObjectSize (0.28 seconds)
=== RUN TestObjectOpen
--- PASS: TestObjectOpen (0.62 seconds)
=== RUN TestObjectUpdate
--- PASS: TestObjectUpdate (2.69 seconds)
=== RUN TestObjectStorable
--- PASS: TestObjectStorable (0.27 seconds)
=== RUN TestLimitedFs
--- PASS: TestLimitedFs (0.56 seconds)
=== RUN TestLimitedFsNotFound
--- PASS: TestLimitedFsNotFound (0.55 seconds)
=== RUN TestObjectRemove
--- PASS: TestObjectRemove (1.35 seconds)
=== RUN TestObjectPurge
--- PASS: TestObjectPurge (2.00 seconds)
=== RUN TestFinalise
--- PASS: TestFinalise (0.00 seconds)
=== RUN TestPutCaseCorrectDirectoryName
--- PASS: TestPutCaseCorrectDirectoryName (0.00 seconds)
=== RUN TestPutCaseCorrectDirectoryNameEmptyComponent
--- PASS: TestPutCaseCorrectDirectoryNameEmptyComponent (0.00 seconds)
=== RUN TestPutCaseCorrectDirectoryNameEmptyParent
--- PASS: TestPutCaseCorrectDirectoryNameEmptyParent (0.00 seconds)
=== RUN TestGetPathWithCorrectCase
--- PASS: TestGetPathWithCorrectCase (0.00 seconds)
=== RUN TestPutAndWalk
--- PASS: TestPutAndWalk (0.00 seconds)
=== RUN TestPutAndWalkIncompleteTree
--- PASS: TestPutAndWalkIncompleteTree (0.00 seconds)
PASS
ok      github.com/ncw/rclone/dropbox   25.932s

**Comment by ncw** [comment]
Note it is the integration tests which fail

```
cd $GOPATH/src/github.com/ncw/rclone/fs
go test -v --remote TestDropbox: --subdir

=== RUN TestSizeSuffixString
--- PASS: TestSizeSuffixString (0.00s)
=== RUN TestSizeSuffixSet
--- PASS: TestSizeSuffixSet (0.00s)
=== RUN TestInit
--- PASS: TestInit (1.65s)
	operations_test.go:73: Testing with remote Dropbox root '7jbygeeds6cn1zrc0sm7h64q2mkchrew/s7rlu27g'
	operations_test.go:80: Testing with local "/tmp/rclone654934112"
=== RUN TestCalculateModifyWindow
--- PASS: TestCalculateModifyWindow (0.00s)
	operations_test.go:89: ModifyWindow is "1ns"
=== RUN TestMkdir
--- PASS: TestMkdir (1.08s)
=== RUN TestCopyWithDryRun
--- PASS: TestCopyWithDryRun (0.67s)
=== RUN TestCopy
2015/06/10 17:16:27 Not found "sub dir/hello world"
--- FAIL: TestCopy (3.15s)
	fstest.go:96: 1 objects not found
=== RUN TestLsd
--- PASS: TestLsd (0.22s)
=== RUN TestCopyAfterDelete
2015/06/10 17:16:27 Not found "sub dir/hello world"
--- FAIL: TestCopyAfterDelete (0.23s)
	fstest.go:96: 1 objects not found
=== RUN TestCopyRedownload
2015/06/10 17:16:27 Not found "sub dir/hello world"
2015/06/10 17:16:28 Not found "sub dir/hello world"
--- FAIL: TestCopyRedownload (0.49s)
	fstest.go:96: 1 objects not found
	fstest.go:96: 1 objects not found
	operations_test.go:375: Cleaning temporary directory: "/tmp/rclone654934112"
=== RUN TestSyncBasedOnCheckSum
--- FAIL: TestSyncBasedOnCheckSum (4.32s)
	operations_test.go:375: Cleaning temporary directory: "/tmp/rclone654934112"
	operations_test.go:207: We synced, though we shouldn't have.
=== RUN TestSyncAfterChangingModtimeOnly
2015/06/10 17:16:34 Not found "empty space"
--- FAIL: TestSyncAfterChangingModtimeOnly (2.07s)
	fstest.go:83: Unexpected file "check sum"
	fstest.go:96: 1 objects not found
=== RUN TestSyncAfterAddingAFile
2015/06/10 17:16:37 Not found "empty space"
2015/06/10 17:16:37 Not found "potato"
--- FAIL: TestSyncAfterAddingAFile (2.51s)
	fstest.go:83: Unexpected file "check sum"
	fstest.go:96: 2 objects not found
=== RUN TestSyncAfterChangingFilesSizeOnly
2015/06/10 17:16:40 Not found "empty space"
2015/06/10 17:16:40 Not found "potato"
--- FAIL: TestSyncAfterChangingFilesSizeOnly (3.01s)
	fstest.go:83: Unexpected file "check sum"
	fstest.go:96: 2 objects not found
=== RUN TestSyncAfterChangingContentsOnly
2015/06/10 17:16:42 Not found "empty space"
2015/06/10 17:16:42 Not found "potato"
--- FAIL: TestSyncAfterChangingContentsOnly (2.66s)
	fstest.go:83: Unexpected file "check sum"
	fstest.go:96: 2 objects not found
=== RUN TestSyncAfterRemovingAFileAndAddingAFileDryRun
2015/06/10 17:16:43 Not found "empty space"
2015/06/10 17:16:43 Not found "potato"
--- FAIL: TestSyncAfterRemovingAFileAndAddingAFileDryRun (0.66s)
	fstest.go:83: Unexpected file "check sum"
	fstest.go:96: 2 objects not found
=== RUN TestSyncAfterRemovingAFileAndAddingAFile
2015/06/10 17:16:46 Not found "empty space"
2015/06/10 17:16:46 Not found "potato2"
--- FAIL: TestSyncAfterRemovingAFileAndAddingAFile (2.93s)
	fstest.go:83: Unexpected file "check sum"
	fstest.go:96: 2 objects not found
=== RUN TestLs
--- FAIL: TestLs (0.23s)
	operations_test.go:331: empty space missing: ""
	operations_test.go:334: potato2 missing: ""
=== RUN TestLsLong
--- FAIL: TestLsLong (0.26s)
	operations_test.go:347: empty space missing: ""
	operations_test.go:351: potato2 missing: ""
=== RUN TestMd5sum
--- FAIL: TestMd5sum (0.23s)
	operations_test.go:363: empty space missing: ""
	operations_test.go:366: potato2 missing: ""
=== RUN TestCheck
--- PASS: TestCheck (0.00s)
=== RUN TestFinalise
--- PASS: TestFinalise (1.74s)
	operations_test.go:375: Cleaning temporary directory: "/tmp/rclone654934112"
FAIL
exit status 1
FAIL	github.com/ncw/rclone/fs	28.126s
```

**Comment by shalupov** [comment]
Sorry, for whatever reason I thought it's enough to add TestDropbox remote.

**Comment by ncw** [comment]
No worries!  The above is what I noticed when merging your code and running the integration tests.

**Comment by shalupov** [comment]
Check it now, please

**Comment by ncw** [comment]
Looks good to me!

I've merged it - thank you very much, and it wll be in the next release.

Note that I rebased, squashed and gofmted it.

Thank you very much for your contribution

-- Nick

**Pull request closed without merging**
