### PR TITLE
cache: clean root path

### LINKED ISSUE #1945: Cache backend: Crash when a / character is written as the root dir
## Version
rclone v1.39
os/arch: linux/amd64
go version: go1.9.2

## Command
The commands that crashes with the cache backend works fine for plain or encrypted gdrive.

### Crashes (see log below):
rclone lsd gdrive_cached:/
rclone lsd gdrive_cached:/any_directory

### Lists directories successfully:
rclone lsd gdrive_cached:
rclone lsd gdrive_cached:any_directory
## Log

```
2017/12/26 12:29:45 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2017/12/26 12:29:45 DEBUG : rclone: Version "v1.39" starting with parameters ["rclone" "-vv" "lsd" "gdrive_cached:/"]
2017/12/26 12:29:46 DEBUG : gdrive_cached: wrapped gdrive:media at root /
2017/12/26 12:29:46 INFO  : gdrive_cached: Cache DB path: /home/user/.cache/rclone/cache-backend/gdrive_cached.db
2017/12/26 12:29:46 INFO  : gdrive_cached: Cache chunk path: /home/user/.cache/rclone/cache-backend/gdrive_cached
2017/12/26 12:29:46 INFO  : gdrive_cached: Chunk Memory: true
2017/12/26 12:29:46 INFO  : gdrive_cached: Chunk Size: 5M
2017/12/26 12:29:46 INFO  : gdrive_cached: Chunk Total Size: 10G
2017/12/26 12:29:46 INFO  : gdrive_cached: Chunk Clean Interval: 1m0s
2017/12/26 12:29:46 INFO  : gdrive_cached: Workers: 4
2017/12/26 12:29:46 INFO  : gdrive_cached: File Age: 6h0m0s
2017/12/26 12:29:46 INFO  : gdrive_cached: Cache Writes: false
2017/12/26 12:29:46 INFO  : gdrive_cached:/: Modify window is 1ms
panic: runtime error: slice bounds out of range

goroutine 40 [running]:
github.com/ncw/rclone/cache.(*Directory).Remote(0xc4203d4e00, 0x4, 0x4)
        /tmp/nix-build-rclone-1.39.drv-0/go/src/github.com/ncw/rclone/cache/directory.go:98 +0x117
github.com/ncw/rclone/cache.(*Persistent).GetDirEntries.func1(0xc42046c9a0, 0xff8f40, 0xc42046c9a0)
        /tmp/nix-build-rclone-1.39.drv-0/go/src/github.com/ncw/rclone/cache/storage_persistent.go:204 +0x2d5
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*DB).View(0xc4201663c0, 0xc420048ae0, 0x0, 0x0)
        /tmp/nix-build-rclone-1.39.drv-0/go/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/db.go:680 +0x9a
github.com/ncw/rclone/cache.(*Persistent).GetDirEntries(0xc4203d6640, 0xc4203d4e00, 0x0, 0xc4203d4e00, 0xc420048b68, 0x41355c, 0xc420048b68)
        /tmp/nix-build-rclone-1.39.drv-0/go/src/github.com/ncw/rclone/cache/storage_persistent.go:182 +0x7d
github.com/ncw/rclone/cache.(*Fs).List(0xc420095860, 0x0, 0x0, 0x0, 0xc420033300, 0x0, 0x0, 0x0)
        /tmp/nix-build-rclone-1.39.drv-0/go/src/github.com/ncw/rclone/cache/cache.go:461 +0xb3
github.com/ncw/rclone/fs.ListDirSorted(0x15a2cc0, 0xc420095860, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/nix-build-rclone-1.39.drv-0/go/src/github.com/ncw/rclone/fs/operations.go:629 +0x63
github.com/ncw/rclone/fs.walk.func2(0xc4204a3d40, 0xc42006ab40, 0xff8b28, 0x15a2cc0, 0xc420095860, 0x0, 0xc4204a3d38, 0xc4204d1980, 0xc4204a3d50, 0xc42019d230, ...)
        /tmp/nix-build-rclone-1.39.drv-0/go/src/github.com/ncw/rclone/fs/walk.go:120 +0x1e3
created by github.com/ncw/rclone/fs.walk
        /tmp/nix-build-rclone-1.39.drv-0/go/src/github.com/ncw/rclone/fs/walk.go:112 +0x265
```

### PR DESCRIPTION
**Pull request by B4dM4n**
Trim "/" from the root path to fix "slice bounds out of range" panic in directory.go:98.

Fixes #1945

### CODE REVIEW

**Comment by ncw** [comment]
@remusb can you take a look at this?  It looks OK to me. Thanks.

**Comment by remusb** [comment]
👍 

Sadly I pushed something else before this. Can you fix the conflict? I'll merge it after that.
Just to confirm, did this fixed the issue? I checked the difference between TrimPrefix and Trim and there shouldn't be any difference on a rootPath `/` but I never actually tested it in practice with what got passed.

@B4dM4n

**Comment by B4dM4n** [comment]
Ok, i will rebase it. 

> Just to confirm, did this fixed the issue? I checked the difference between TrimPrefix and Trim and there shouldn't be any difference on a rootPath / but I never actually tested it in practice with what got passed.

`Trim` fixed the issue. The issue was that `path.Clean` removed the leading /, but the stored `root` could still have it. This caused the `slice bounds out of range` panic, because `len(f.Root())` > `len(p)` in `cache.go#L1270`.

I didn't check either, whether `TrimPrefix` would be enough to fix this issue.

**Comment by remusb** [comment]
Great. You should have permission now to merge so feel free to do it whenever you want :)

**Comment by B4dM4n** [comment]
Right, I did not want to wait for the tests to finish last night :smiley:

**Pull request merged**
