### PR TITLE
Add support to aliyun-oss

### PR DESCRIPTION
**Pull request by luolibin**

### CODE REVIEW

**Comment by luolibin** [comment]
Can you add dependency locally,the dep tool have some problem.

**Comment by ncw** [comment]
The problem with the dep tool is that we need https://github.com/aliyun/aliyun-oss-go-sdk/pull/76 to be merged.

Do you know anyone at aliyun to ask about it?

**Comment by luolibin** [comment]
It seem that they do not want to open http.client. Are there any other solutions?

**Comment by ncw** [comment]
The other solution would be not to use the  aliyun/aliyun-oss-go-sdk and use rclone's rest module instead.

**Comment by nczz** [comment]
oh... We are really want this feature....

**Comment by ncw** [comment]
The OSS team have finally merged my patch (or re-implemented it, I'm not sure), so I've fixed the bitrot for the oss backend and have merged it to the [oss branch](https://github.com/ncw/rclone/tree/oss).

I've made all the tests pass, I just need to write the docs!

Thank you for your help @luolibin :-)  I'm going to close this pull request now.

Here is the first beta.  No docs yet!  The backend is called "oss" if anyone wants to try:

https://beta.rclone.org/branch/v1.45-094-g3d1958f4-oss-beta/ (uploaded in 15-30 mins) (uploaded in 15-30 mins)

**Comment by luolibin** [comment]
Thank you very much!



75738947@qq.com
 
From: Nick Craig-Wood
Date: 2019-01-11 06:16
To: ncw/rclone
CC: luolibin; Mention
Subject: Re: [ncw/rclone] Add support to aliyun-oss (#1920)
The OSS team have finally merged my patch (or re-implemented it, I'm not sure), so I've fixed the bitrot for the oss backend and have merged it to the oss branch.
I've made all the tests pass, I just need to write the docs!
Thank you for your help @luolibin :-) I'm going to close this pull request now.
Here is the first beta. No docs yet! The backend is called "oss" if anyone wants to try:
https://beta.rclone.org/branch/v1.45-094-g3d1958f4-oss-beta/ (uploaded in 15-30 mins) (uploaded in 15-30 mins)

**Pull request closed without merging**
