### PR TITLE
Add Scaleway to rclone documentation

### PR DESCRIPTION
**Pull request by sieben**
#### What is the purpose of this change?

Scaleway is offering a S3 compatible product. The goal of this PR is to inform rclone users that they can use Scaleway object storage with rclone.

### CODE REVIEW

**Comment by sieben** [comment]
I don't think my code broke the build. Can I get some help about how to get this documentation PR merged? :)

**Comment by ncw** [comment]
Sorry for the delay, been a bit busy!

Your PR looks fine - will merge it in a moment, thank you.  It didn't break the build, don't worry!

**Comment by sieben** [comment]
Thanks @ncw do you know when the website will be updated?

**Comment by ncw** [comment]
It will be updated at the next release on 7th Feb.  You can checkout https://tip.rclone.org in the meantime

**Comment by sieben** [comment]
I don't find Scaleway on the homepage of this website :/ How can I make it
happen?

Le sam. 2 févr. 2019 à 13:35, Nick Craig-Wood <notifications@github.com> a
écrit :

**Comment by ncw** [comment]
> I don't find Scaleway on the homepage of this website :/ How can I make it happen?

Wait until 2019-02-07 for the v1.46 release :-)

**Pull request merged**
