### PR TITLE
initial import of remote serve

### PR DESCRIPTION
**Pull request by vtolstov**
Signed-off-by: Vasiliy Tolstov <v.tolstov@selfip.ru>

### CODE REVIEW

**Comment by vtolstov** [comment]
@ncw  please check this, i have a problem with lsd inside another dir and ls inside dir.
may be i miss something...

**Comment by vtolstov** [comment]
url for test http://cdn.swiftbird.org/

**Comment by ncw** [comment]
If you make this change, then you can use `-vv --dump-bodies` and you can see clearly what is wrong

```diff
diff --git a/serve/serve.go b/serve/serve.go
index a1e8df2..96dd87f 100644
--- a/serve/serve.go
+++ b/serve/serve.go
@@ -78,12 +78,7 @@ func NewFs(name, root string) (fs.Fs, error) {
 		port = "80"
 	}
 
-	tr := &http.Transport{
-		MaxIdleConns:       10,
-		IdleConnTimeout:    30 * time.Second,
-		DisableCompression: false,
-	}
-	client := &http.Client{Transport: tr}
+	client := fs.Config.Client()
 
 	_, err := client.Head(host + ":" + port)
 	if err != nil {
```

    rclone ls -vv --dump-bodies serve:atomic

```
2017/02/23 13:24:33 DEBUG : HEAD /atomicatomic HTTP/1.1
```

**Comment by vtolstov** [comment]
THanks! I'm fix my ugly code =). Now rclone lsd and rclone ls can output listing. 
Does i need something specific for mount command?
Also - does it possible to force when mount to readonly mode ?

**Comment by vtolstov** [comment]
@ncw can you check my code ?

**Comment by vtolstov** [comment]
also if i have two servers or more that serve identical content, does it possible to add to fs.Config.Client ability to round-robin each endpoint or do failover? 
and what happening when remote when request arrived not responding, but after one second works fine - does rclone mount supports reconnection ability or it fails with transport endpoint not connected?

**Comment by vtolstov** [comment]
i found packages that can act as load balancers, but may be we need to reimplement something like this inside rclone? What do you think ?
https://godoc.org/github.com/olivere/balancers 
https://godoc.org/github.com/linkosmos/rehttp

**Comment by ncw** [comment]
> Does i need something specific for mount command?

I don't think so

> Also - does it possible to force when mount to readonly mode 

`--read-only` flag for mount will do it

> also if i have two servers or more that serve identical content, does it possible to add to fs.Config.Client ability to round-robin each endpoint or do failover?

If you put both the IPs into the DNS then the transport will round robin them I think.

> and what happening when remote when request arrived not responding, but after one second works fine - does rclone mount supports reconnection ability or it fails with transport endpoint not connected?

The mount will retry failed opens

**Comment by vtolstov** [comment]
> If you put both the IPs into the DNS then the transport will round robin them I think.

this is not possible, firstly because i have more than one hostname, also path can be different but contents is the same, for example see the various mirrors...

**Comment by vtolstov** [comment]
@ncw i'm fix all my issues. So by providing http endpoiny i can list and mount any path.

**Comment by ncw** [comment]
>  i'm fix all my issues. So by providing http endpoint i can list and mount any path

Nice one!

Do you want me to merge this as a sort of special purpose remote?

If so can you squash all the commits and separate the vendor changes from code changes?

It needs some docs, and some tests too ideally, though the normal integration tests won't work if the remote can't read and write.

I think we should probably rename it to be the `http` remote which makes more sense than calling it the `serve` remote.

**Comment by vtolstov** [comment]
@ncw ok, i'm squash and add vendoring in separate commit.

**Comment by vtolstov** [comment]
I'm switch base branch, squash and separate deps commit. Sorry i don't know hot to write tests =(

**Comment by vtolstov** [comment]
build failed for strange reasons in travis with go 1.8.
Can you suggest me or write tests ? What i need? Does i need t spawn http server and connect it to this remote ?

**Comment by vtolstov** [comment]
gentle ping..

**Comment by ncw** [comment]
Sorry have been busy with home life (wife been in hospital)!  Also trying to get the 1.36 release out the door!

> build failed for strange reasons in travis with go 1.8.

It looks like the goimports check is failing... Just format the code with goimports.

> Can you suggest me or write tests ? What i need? Does i need t spawn http server and connect it to this remote ?

In an ideal world you'd use the auto-generated tests that all the other remotes have.  However that isn't going to work since your remote is read-only :-(

The easiest way of testing will be with https://golang.org/pkg/net/http/httptest/

You then use that to test each individual part of your remote - a simple example here: https://gist.github.com/cespare/4992458

**Comment by vtolstov** [comment]
goimports fixed

**Comment by ncw** [comment]
Apologies for the delay - been very busy with home and work life.

I've been having a go with this prior to merging into master.

It works very well for your test URL, but when I tried it with some other examples
  * https://www.craig-wood.com/nick/pub/
  * http://beta.rclone.org/

The results were mixed, including adding `./` in the remote names, and including the URLS with `&` in.

That makes me think that this module needs a test suite.  It should be able to simlulate various different types of web server (have some stored output from various web browsers to make sure the parsing of the page works properly).

The parsing also needs to be stricter so it includes `http://example.com/file` but not `http://example.com/file&size=43` or `http://example.com/subdir/file/`

What do you think about adding a test suite and trying to make it more generic?

I merged this into a branch "http" along with some fixes from me - send future PRs against that branch.

PS you can test new remotes like this

```RCLONE_CONFIG_HLS_TYPE=http RCLONE_CONFIG_HLS_ENDPOINT=http://beta.rclone.org/ rclone lsl hls:```

**Comment by vtolstov** [comment]
Thanks! I'm try to fix issues.

**Comment by vtolstov** [comment]
What do you think about filter-out files which names contains ? & nbsp;

**Comment by vtolstov** [comment]
please check new pr, and as i understand i need to create 3 tests:
* nginx
* apache
* caddy

**Comment by ncw** [comment]
Just show you know I've merged this to master now along with tests and docs.

Thank you very much for contributing it, and sorry it has taken me such a long time.

-- Nick

**Comment by vtolstov** [comment]
Bit thanks! And sorry for absent test (i'm forget about it =().
Thanks again and waiting for new release =)

**Pull request closed without merging**
