### PR TITLE
WIP: 1fichier Support

### PR DESCRIPTION
**Pull request by fionera**
#### What is the purpose of this change?
Add Support for 1fichier

#### Was the change discussed in an issue or in the forum before?
https://github.com/ncw/rclone/issues/2908

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by fionera** [comment]
This PR is work in progress. I will squash the commits when done

**Comment by ncw** [comment]
Look forward to seeing your progress!

Can I suggest that you use the lib/rest library for http communcations.  Check out the box backend for examples.

**Comment by fionera** [comment]
The dont have a rest api :/ listing and download is already implemented but currently looking how to make the root working.

**Comment by ncw** [comment]
> The dont have a rest api :/ 

Looking at your code it seems that their API is based on HTTP and JSON - that will work really well with `lib/rest`.

> listing and download is already implemented but currently looking how to make the root working.

**Comment by fionera** [comment]
Since I currently dont have much time and 1fichier introduced a new limit I will not continue on this fork... Sorry :/

**Comment by ncw** [comment]
> Since I currently dont have much time and 1fichier introduced a new limit I will not continue on this fork... Sorry :/

No worries.  Maybe things will change in the future!

**Comment by bingoxo** [comment]
@fionera do you mind taking a look at this : https://gitlab.com/BylonAkila/astreamfs

**Pull request closed without merging**
