### PR TITLE
dlna: add connection manager service description

### PR DESCRIPTION
**Pull request by sretlawd**
The UPnP MediaServer spec says that the ConnectionManager service is
required, and adding it was enough to get dlna support working on my
other TV (LG webOS 2.2.1).

#### What is the purpose of this change?

Improve device compatibility & spec compliance by adding an additional service descriptor for ConnectionManager v1.  Through lots of trial and error, I found this to be the missing piece to
get dlna working on my LG webOS 2.2.1 TV.

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [X] I have added tests for all changes in this PR if appropriate.
- [X] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by sretlawd** [comment]
Ah - I should add this doesn't actually implement the ConnectionManager interface, it just advertises it, but that's all that was necessary to get it working on my TV.  I can look at what a minimal actual implementation would be, just to avoid false advertising.

**Comment by ncw** [comment]
> The UPnP MediaServer spec says that the ConnectionManager service is
> required, and adding it was enough to get dlna support working on my
> other TV (LG webOS 2.2.1).
> 
> Improve device compatibility & spec compliance by adding an additional service descriptor for ConnectionManager v1. Through lots of trial and error, I found this to be the missing piece to
> get dlna working on my LG webOS 2.2.1 TV.

Nice one :-)

> Ah - I should add this doesn't actually implement the ConnectionManager interface, it just advertises it, but that's all that was necessary to get it working on my TV. I can look at what a minimal actual implementation would be, just to avoid false advertising.

What does the `ConnectionManager` interface do?  Is it likely to cause problems advertising an interface which isn't there?

**Comment by sretlawd** [comment]
> What does the `ConnectionManager` interface do? Is it likely to cause problems advertising an interface which isn't there?

I don't think it can cause problems not to implement it, but there's probably some device out there that won't work until it is implemented.  Looking at a couple other open source implementations:  Emby Server implements only the getProtocolInfo method, which basically returns which mime types can be played over http.  Minidlnad implements that one plus returns dummy data for a couple other methods.  Doesn't look important at all, it's just typical overengineered design by committee stuff, like all of UPnP..

**Comment by tabnk** [comment]
This PR partially fixed issue #3050. Oculus Go can now view and play media files from rclone (DLNA) via Google Drive. 

However, LG TV (LG LM6200 model 2012) TV crash (restart itself) when rclone (DLNA) was selected.

**Comment by beredim** [comment]
@tabnk
LG LM6200 would be a pre-webos era model, correct?
Does it have latest f/w installed, and how does it behave with other DLNA servers?

**Comment by tabnk** [comment]
@beredim yes, it is pre-webos model.  Latest firmware installed. 

Serviio, Universal Media Server etc work fine my LG TV.

**Comment by ncw** [comment]
OK I'll merge this as it is definitely an improvement - thank you :-)

**Pull request merged**
