### PR TITLE
b2: Fix link sharing #3314

### PR DESCRIPTION
**Pull request by yparitcher**
#### What is the purpose of this change?

make the download auth use the correct path
add a `hasPermission` func to check if the applicationkey can share files
add docs for `downloadurl` re public bucket
#### Was the change discussed in an issue or in the forum before?
#3314

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [X] I have added tests for all changes in this PR if appropriate.
- [X] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
The integration tests for B2 are failing for the link sharing, alas

https://pub.rclone.org/integration-tests/2019-07-05-050026/

It looks like the tests are expecting a lot more of b2 than it can deliver.

What do you think?
```
"go test -v -timeout 30m0s -remote TestB2: -verbose -test.run '^TestIntegration$/^FsMkdir$/^FsPutFiles$/^PublicLink$'" - Starting (try 5/5)
=== RUN   TestIntegration
=== RUN   TestIntegration/FsMkdir
=== RUN   TestIntegration/FsMkdir/FsPutFiles
=== RUN   TestIntegration/FsMkdir/FsPutFiles/PublicLink
2019/07/05 05:13:06 DEBUG : file name.txt: Deleting (id "4_zbfb2cd3380cdcb0b6fb80e1b_f1198fb8b241037a9_d20190705_m051305_c001_v0001090_t0022")
2019/07/05 05:13:06 DEBUG : file name.txt: Deleting (id "4_zbfb2cd3380cdcb0b6fb80e1b_f1198fb8b2410379b_d20190705_m051300_c001_v0001090_t0022")
2019/07/05 05:13:06 DEBUG : hello? sausage/êé/Hello, 世界/ " ' @ < > & ? + ≠/z.txt: Deleting (id "4_zbfb2cd3380cdcb0b6fb80e1b_f1198fb8b241037a1_d20190705_m051302_c001_v0001090_t0022")
--- FAIL: TestIntegration (9.91s)
    fstests.go:358: Using remote "TestB2:"
    --- FAIL: TestIntegration/FsMkdir (8.19s)
        --- FAIL: TestIntegration/FsMkdir/FsPutFiles (6.50s)
            --- FAIL: TestIntegration/FsMkdir/FsPutFiles/PublicLink (0.15s)
                require.go:248: 
                    	Error Trace:	fstests.go:1391
                    	Error:      	An error is expected but got nil.
                    	Test:       	TestIntegration/FsMkdir/FsPutFiles/PublicLink
                    	Messages:   	Expected to get error when file doesn't exist
FAIL
exit status 1
FAIL	github.com/ncw/rclone/backend/b2	9.918s
"go test -v -timeout 30m0s -remote TestB2: -verbose -test.run '^TestIntegration$/^FsMkdir$/^FsPutFiles$/^PublicLink$'" - Finished ERROR in 11.043948934s (try 5/5): exit status 1: Failed [TestIntegration/FsMkdir/FsPutFiles/PublicLink]
```

**Comment by yparitcher** [comment]
as i noted in https://github.com/ncw/rclone/pull/3314#issuecomment-508270846

> however as a side effect it will also happily give a link for a nonexistent path:
> ```
> ./rclone link remote:bucket/nothing/found/here
> https://f002.backblazeb2.com/file/bucket/nothing/found/here?Authorization=zzzzzzz
> ```

since B2 doesn't have folders, i didn't see a way to check if a directory actualy exists.

however i just realized (while looking at this) that is what the `f.root` and `remote` are so all i have to do to fix this is change 

https://github.com/ncw/rclone/blob/5433021e8b0d517c134da6a81d51c787403db1ac/backend/b2/b2.go#L1230 

to first check if `remote` is an object or if `f.root` is a directory.

sorry about that, 
will open a pull request to fix on sunday

**Comment by yparitcher** [comment]
i figured out how to test if a given `f.root, remote` is a file, however i don't see any way in B2 to check if it is a Directory, i don't think it was ever implemented.
```go
	_, err = f.NewObject(ctx, remote)
	if err != nil && err != fs.ErrorNotAFile {
		// FIXME check if Directory
		return "", err
	}
	absPath := "/" + path.Join(f.root, remote)
```
being that B2 is bucket based it is not straightforward, but it should be possible by using the `list` function somehow, but i cant seem to figure it out.

when you have a chance please help me with this.
thanks

**Comment by ncw** [comment]
Apologies for the delay in responding, I've been on vacation.

Where did we get to with this?

**Comment by yparitcher** [comment]
Right now this is failing the tests as i only validate if the DownloadAuthorization call is valid, not if the path is a valid folder or directory.

in my branch:
 https://github.com/yparitcher/rclone/blob/12285822f7edf65c518bff38ee1de0389eb32db6/backend/b2/b2.go#L1222-L1249
i fixed checking if the path is a valid file, however since B2 is bucket based, i could not figure out a way to check if a path is a valid directory.

if you can help me with that this should be finished.
thanks

**Comment by ncw** [comment]
I've added a new error which the tests will take note of `fs.ErrorCantShareDirectories` in 
5a44bafa4e46ad0530ec80f8d3fc4119f7bee73b (I needed this for a new backend I'm writing).

So I think something like this (untested) should do it...  It doesn't strictly speaking detect a directory or not, but I think it will work - what do you think? Detecting directories is very hard on bucket based remotes... You basically need to list them.

```patch
+	if remote == "" || strings.HasSuffix(remote, "/") {
+		return "", fs.ErrorCantShareDirectories
+	}
+	_, err = f.NewObject(ctx, remote)
+	if err == fs.ErrorObjectNotFound || err == fs.ErrorNotAFile {
+		return "", fs.ErrorCantShareDirectories
+	} else if err != nil  {
+		return "", nil
+ }
```

**Comment by yparitcher** [comment]
fixed in #3377

**Pull request merged**
