### PR TITLE
Add async copy buffering

### PR DESCRIPTION
**Pull request by klauspost**
Edit: Can be merged after review.

Proposal for #164 - This adds 4x4MB async buffers to the input when copying files.

This needs a little polish before begin ready for a merge, but should give a general impression.

It should be adjusted for input size, so it is only added when files are above a certain size.

### CODE REVIEW

**Comment by klauspost** [comment]
Uploading from harddrive. Ordinary Performance:
noload

If I copy files to it, while rclone is reading from it, this is the performance:
with-load-no-buffer

If I add the buffer logic, this is the performance:
with-load-and-buffer

**Comment by ncw** [comment]
Looks very interesting!  I won't be able to study it until tomorrow though. Thanks - Nick

**Comment by klauspost** [comment]
The only real downside is that it will not be able to begin reading before 1 buffer is filled. However, it should only rarely have an impact on the total transfer time, unless reads are really slow AND writes are slow.

Also, if the input reader "short reads", the buffer is returned at once, without attempting to fill it.

Right now it is also only applied if the input file is >10MB, which should limit its potential downsides.

**Comment by klauspost** [comment]
It should be ok for review now. I have added tests to feel confident in it, and made it even more transparent in terms of error handling.

**Comment by ncw** [comment]
@klauspost super thanks!  Will review a bit later today.  Can you squash the branch for ease of review?

**Comment by klauspost** [comment]
Done :)

**Comment by klauspost** [comment]
I have implemented you suggestions, except for `io.ReadFull` - the rest made perfect sense and made everything more readable.

I have added `io.WriterTo`, since it seemed like a very good idea. I am pretty sure that will also provide speedups in other cases, where the writer "likes" big writes, and it saves a ton of function calls.

I haven't squashed the commits, since I wasn't sure it github would delete your comments on a non-existing commit.

**Comment by ncw** [comment]
That looks great now.  I'm happy to merge it now and tweak it as we get some more experience with it.  Does that sound OK to you?  If so can you rebase and squash as you see fit.

Thanks

Nick

**Comment by klauspost** [comment]
ok, it did actually delete your comments - good to know.

I squashed it, and fixed a bug in WriterTo (it didn't actually implement the interface - that is now tested).

**Comment by klauspost** [comment]
OK, I added some more tests, so coverage is now 98.7%

You can merge now, I am fairly confident this works as intended.

**Comment by ncw** [comment]
I've merged that - thanks Klaus.

I'll give it a good thrashing and try to get some performance numbers too.

Thanks

Nick

**Pull request closed without merging**
