### PR TITLE
Added Azure Blob storage support

### PR DESCRIPTION
**Pull request by adragomir**
Hey I started working on Azure blob storage support (based largely on S3). 
I tested largely the sync command, the checksums look okay, but there are no automated tests for now. 

Let me know what needs work . 

Thanks for taking a look !

### CODE REVIEW

**Comment by ncw** [comment]
That is looking really good :-)

Some small stuff
* Can you link the commit message to #801
* Can you split the vendor commit into a separate commit "vendor: add xyz for azure"?
* Fix the build! (I think you've missed actually committing the stuff in vendor)

I presume you've seem the docs on how to [write a new backend](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#writing-a-new-backend)? You've got to "unit tests" by the look of it - if you generate them for Azure, then they will guide you through making it 100% compliant with the rest of rclone.

Excuse my ignorance but are there different types of Azure storage?  This just addresses blobs - will there be a requirement for people for the other types of storage? I'm wondering whether it might be better called "azureblob" but happy to go with your recommendation.

Anyway, great stuff - carry on :-)

**Comment by adragomir** [comment]
@ncw thanks for the feedback ! I'm traveling next week, but I'll get on it ASAP (should I close the PR until then so I don't pollute ?). ACK for all the requested changes, and also I think `azureblob` is better. Thanks for the suggestion on how to do unit tests as well.

For Azure there's actually a bunch of storages (sic), but let's say the usual ones are blob and file: 
* https://docs.microsoft.com/en-us/azure/storage/storage-introduction#blob-storage
* https://docs.microsoft.com/en-us/azure/storage/storage-introduction#file-storage

Files are actually mountable as a CIFS mount, so maybe less interesting to rclone, as other solutions exist, but we need blob.

**Comment by ncw** [comment]
Looking forward to seeing your changes!

Happy for you to keep force pushing this PR if that makes a good workflow for you.

The tests are quite fussy, so let me know if you need any help getting them to pass.

**Comment by psallis** [comment]
Would love to see Azure Storage added.

**Comment by ncw** [comment]
How are you doing with this?

I have to make an pology - I've just changed the List interface, splitting it into a simple List which just lists one directory, and a ListR interface with does a recursive list if the remote is capable of it. This takes a lot of complexity out of the remotes which is a good thing hopefully! If you take a look at the S3 remote you'll see [how it has changed](https://github.com/ncw/rclone/commit/8a6a8b9623bea1f600ad15eec2dc74ed37e65110#diff-7db3cb93944d57b2ffc803281c906018)

**Comment by ncw** [comment]
I'd like to get this into 1.38 if possible.  Do you want me to carry on from this point?

**Comment by adragomir** [comment]
@ncw hey Nick, sorry for the absence. I'd love it if you could carry this forward, if you think this is useful enough. Sorry I haven't been able to port and succesfully close the PR.

**Comment by ncw** [comment]
@adragomir that is perfectly fine - you've done the hard bit which is much appreciated.  I'll pull this into a branch and finish it off.

**Comment by ncw** [comment]
I've taken what you've done and fixedup bitrot for rclone changes, and again for the Azure library (which seems to have changed a great deal) and it is now passing the integration tests!

I've a bit more work to do to support large blobs.  I'd like to support modtime also which means adding a bit of metadata with the modtime in also.

I'm going to close this now and I'll update #801 when I've made a beta with the code in.

Thank you very much for your contribution

-- Nick

**Pull request closed without merging**
