### PR TITLE
Gdrive: partial responses by using explicit fields

### PR DESCRIPTION
**Pull request by azgul**
This solves #1346

The fields I included should be the absolute minimum required to pass the integration tests.

It only seemed to be applicable in listAll()

### CODE REVIEW

**Comment by ncw** [comment]
I've squashed and merged that - thank you very much.

I note that we don't need `owners` if we aren't using `--drive-auth-owner-only` and the owner seems to be quite voluminous - what do you think about sending another PR which conditonally adds `owners` to the string if that flag is in use?

**Comment by ncw** [comment]
Re-opening this for test comments!

**Comment by ncw** [comment]
Whoops wrong ticket!

**Comment by azgul** [comment]
@ncw sure I'll take a crack at that.

**Pull request closed without merging**
