### PR TITLE
s3: add support for setting storage class in config and command line

### PR DESCRIPTION
**Pull request by askot**
This PR adds support for defining storage class for Amazon S3 object uploads.

I think it is pretty useful for storing backups (e.g. with STANDARD_IA storage class to optimize storage costs).

### CODE REVIEW

**Comment by ncw** [comment]
Looks very nice. Will merge when I get back home early next week. 

Thanks 

Nick

**Comment by askot** [comment]
That's great, thanks! I have updated the pull request to resolve the merge conflict with latest changes.

**Comment by bruno222** [comment]
Thanks @askot! Waiting for this PR to be alive to reduce our costs on S3 :-)

**Comment by ncw** [comment]
I've merged that now (squashed and rebased) - very nice code :-)

Thank you very much for your contribution.

Here is a beta with it in: http://pub.rclone.org/v1.33-22-g7227a26%CE%B2/

**Pull request closed without merging**
