### PR TITLE
Support for FTP backend

### PR DESCRIPTION
**Pull request by arcimboldo**
Hi all,

this is preliminary work to add FTP support, as per issue #540. It is not perfect, and doc is still missing, but I would like to have someone to play with it already because I'm not that familiar with Go.

Also, I've tested with vsftpd and it works (both anonymous and user/password access), but for some reason it doesn't work with, e.g., ftp.kernel.org.

### CODE REVIEW

**Comment by ab30000** [comment]
I'd like to test this but know nothing about go -- what would I do to get your FTP version working?

**Comment by arcimboldo** [comment]
I don't know much myself, I'm still learning. To make it work I had to download my git repo to $GOPATH/src/github/ncw/rclone and then run "make" and configure a new Ftp repository with "rclone config"

**Comment by unvency** [comment]
Hello,

do you know how to set up FTP connection? There is no option to configure an ftp profile in rclone config.

Greetings

**Comment by ncw** [comment]
@arcimboldo This looks almost ready to go.  Did you solve the problems with the vendor directory?  if you can do that then travis will start telling you about stuff you need to fix.

Which FTP server have you been testing against BTW?

**Comment by unvency** [comment]
@ncw Do you know where I can configure the FTP login? I cannot found any option in the source code to set it up. And also, there is know selection for FTP in arcimboldo's rclone config

**Comment by ncw** [comment]
@arcimboldo how are you doing with this?  Need any help?

Regards

Nick

**Comment by unvency** [comment]
Dear Nick,
now we are waiting since 3 months for FTP support.

Are there any updates @ncw ?

**Comment by ncw** [comment]
@arcimboldo want me to merge what you've done so far?

**Comment by ncw** [comment]
I'm testing this in the ftp branch - will merge shortly :-)

**Comment by arcimboldo** [comment]
Cool! Let me know if it works...

.a.

**Comment by arcimboldo** [comment]
hi, were you able to merge it? It looks like master changed enough so that
it doesn't properly merge, and I happen to be home sick today, so if you
want I can at least fix the merging.

**Comment by ncw** [comment]
> hi, were you able to merge it? It looks like master changed enough so that
it doesn't properly merge, and I happen to be home sick today, so if you
want I can at least fix the merging.

I fixed up the bitrot in a separate branch.  You can have a go with [it in the ftp branch](https://github.com/ncw/rclone/tree/ftp).

It is working quite well - it passes all the tests :-)  There is a bit more work to be done to make a connection pool for the FTP login connections - that will speed it up greatly.

**Comment by ncw** [comment]
...I'm just leaving this PR open until I have merged the ftp branch to master so I don't forget!

**Comment by ncw** [comment]
I have merged this now :-)

See https://beta.rclone.org/v1.36-114-gcdacf026/ (in 15-30 mins)

**Comment by ncw** [comment]
@arcimboldo thank you very much for contributing this.  I think I've managed to get all the kinks out of it and make it nice and fast - I'd be interested to see what you think!

**Pull request closed without merging**
