### PR TITLE
Add a delete threshold to sync (--max-delete)

### LINKED ISSUE #959: Add a delete threshold to sync (--max-delete)
First, really great piece of software! Very fast!

It would nice to have some kind of `delete threshold` for `sync`. 

Motivation:

I use this to sync several disks with my photo catalog. Sort of like an ongoing backup.

Sometimes I delete files in source, but it is usually mostly add -- so if, say, 200 files are deleted from source, it would be nice to bail out early with a big bold error.

### PR DESCRIPTION
**Pull request by bep**
Fixes #959

### CODE REVIEW

**Comment by bep** [comment]
I see the test errors, will fix.

**Comment by bep** [comment]
The current test failures seems to be unrelated (shaky tests?).

I can add a test + a line in the documentation for this if you can tell me if my implementation makes sense?

**Comment by ncw** [comment]
> The current test failures seems to be unrelated (shaky tests?).

Yes I think you are right.  I've retried the test.

**Comment by ncw** [comment]
> I can add a test + a line in the documentation for this if you can tell me if my implementation makes sense?

I've taken a look at the implementation and it looks good to me :-) Nice use of fatal error for signalling.

A description [in the docs](https://github.com/ncw/rclone/blob/master/docs/content/docs.md#--max-depthn) of `--max-delete` would be great as would a test in [operations_test.go](https://github.com/ncw/rclone/blob/master/fs/operations/operations_test.go)

Thanks!

**Comment by ncw** [comment]
@bep do you want me to merge this?  I'm happy to write the docs if you haven't got the time.

Cheers

Nick

**Comment by bep** [comment]
>@bep do you want me to merge this? 

Please do. I have been busy lately; but I'm using this branch and it works great.

**Comment by ncw** [comment]
I've merged this in ab8c0a81fa0840f501f35954b26d746c8eaf0fea (I had to rebase it manually to fix a conflict).

I stuck some docs in 771fbbe3144fba46d5c69cedf7f1bd38bc1da78b

Thank you very much @bep :-)

**Pull request closed without merging**
