### PR TITLE
Ibmcos support

### PR DESCRIPTION
**Pull request by gbadanahatti**
We have added the IBM COS S3 support as a backend.

### CODE REVIEW

**Comment by ncw** [comment]
This appear to just be copy of the s3 remote?  If so can you add docs for how to configure your cloud storage system into [the s3 docs](https://github.com/ncw/rclone/blob/master/docs/content/s3.md) instead please?  You can also mention it in the [index page for the site](https://github.com/ncw/rclone/blob/master/docs/content/about.md) which will appear on the front page of rclone.org

**Comment by gbadanahatti** [comment]
Hi,  Thanks for taking a look at this. This is not a byte to byte copy of the s3 backend. In the very first iteration we have removed some options that do not apply to IBM COS. In the next iterations in the coming months we will be:

1. Changing the SDK from aws sdk to IBM COS SDK.
2. Tighter integration with IBM IAM. 
3. Service Integration with other IBM Cloud services.

Having a separate backend will facilitate us to start contributing towards the above areas.

**Comment by ncw** [comment]
Ignoring the config changes which can be done without code changes, I see this difference in the code

Which I don't think merits an entire new backend.

```patch
--- s3/s3.go	2018-03-06 12:38:58.335168444 +0000
+++ ibmcos_s3/ibmcos_s3.go	2018-03-13 19:49:12.584583471 +0000
@@ -416,7 +283,6 @@
 		acl:                config.FileGet(name, "acl"),
 		root:               directory,
 		locationConstraint: config.FileGet(name, "location_constraint"),
-		sse:                config.FileGet(name, "server_side_encryption"),
 		storageClass:       config.FileGet(name, "storage_class"),
 	}
 	f.features = (&fs.Features{
@@ -427,9 +293,6 @@
 	if *s3ACL != "" {
 		f.acl = *s3ACL
 	}
-	if *s3StorageClass != "" {
-		f.storageClass = *s3StorageClass
-	}
 	if f.root != "" {
 		f.root += "/"
 		// Check to see if the object exists
@@ -1009,7 +872,7 @@
 	resp, err := o.fs.c.GetObject(&req)
 	if err, ok := err.(awserr.RequestFailure); ok {
 		if err.Code() == "InvalidObjectState" {
-			return nil, errors.Errorf("Object in GLACIER, restore first: %v", key)
+			return nil, errors.Errorf("Object in ARCHIVE TIER, restore first: %v", key)
 		}
 	}
 	if err != nil {
```

Maintaining a backend is a lot of work and I'm sure you'll understand that having another one to maintain which is a 99% duplicate of the s3 backend isn't attractive.

What I'd like you to do for the moment is to add a patch to [the s3 docs](https://github.com/ncw/rclone/blob/master/docs/content/s3.md) describing how to set up the s3 remote to use with ibmcos.  Make a new section with the instructions in with links to where to get the regions from.

You can also add another patch [to the front page of rclone.org](https://github.com/ncw/rclone/blob/master/docs/content/about.md) with a link to the s3 page and your preferred page for ibmcos.

If you can get that in before the weekend then I can put it in the v1.40 release :-)

What might be a good idea is for us to think about how we can add back the configuration you made into the s3 backend.  Maybe what is required is a heirachical configuration which asks for whether you want aws s3/digital ocean/wasabi/ibm cos then has further configuration.

That would improve the user experience of rclone greatly and wouldn't make any code duplication.

I don't think we can get that in before v1.40 though.

**Comment by gbadanahatti** [comment]
Thanks. We will go with the documentation only route for now. I will try to get it before the end of this week.

**Comment by ncw** [comment]
> Thanks. We will go with the documentation only route for now. I will try to get it before the end of this week.

Great - looking forward to it.

I made an issue to think about how to configure the S3 backend better here #2140 - we can re-use your configuration from this pull request there.

**Comment by ncw** [comment]
I'm going to close this one in favour of  #2144

**Pull request closed without merging**
