### PR TITLE
support for zsh auto-completion - #983

### PR DESCRIPTION
**Pull request by bpicode**

### CODE REVIEW

**Comment by ncw** [comment]
Apologies for the delay in responding, I've been on vacation.

Can you separate the commit into two please, one for the vendor stuff (the update of cobra) and one with your actual changes.

I note that this changes the syntax of `rclone genautocomplete` in a backwards incompatible way which is OK since I think it will give a sensible error.

**Comment by ncw** [comment]
Don't worry about splitting the commit - I'll do it shortly!

**Comment by ncw** [comment]
I split the commit into 7e93567b18a822ed8b32428b51ff52e8601da570 and f1f7e0e6f9ea6da5be51a272e94869209aefb487 and merged - thank you very much :-)

**Comment by bpicode** [comment]
Ok, thx. I was going to do it, but you were faster.

**Comment by ncw** [comment]
@bpicode no worries!  Sorry about changing my mind - I thought I'd kept you waiting long enough while I was on vacation.

**Pull request closed without merging**
