### PR TITLE
ftp: new flag to limit the number of parallel connections

### LINKED ISSUE #2166: Ftp with connections limits
#### What is the problem you are having with rclone?

I'm unable to limit the number of parallel FTP connections rclone is making.

#### What is your rclone version (eg output from `rclone -V`)
v1.40-DEV (master)

#### Which OS you are using and how many bits 

Alpine Linux 3.7 docker (https://hub.docker.com/r/speedy37/docker-restic-rclone/)

####  Which cloud storage system are you using? (eg Google Drive)

OVH backup FTP

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone ls ftp:

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2018/03/22 10:35:05 ERROR : ftp://my_host:21: Error while Logging in into my_host:21: 421 I can't accept more than 3 connections as the same user
```

Looking at the ftp backend code, I saw that the pool size is unlimited, having the possibility to limit that would be great.

### PR DESCRIPTION
**Pull request by Speedy37**
Fixes #2166

### CODE REVIEW

**Comment by Speedy37** [comment]
Limiting the pool size cause a deadlock with restic in some cases (check/restore) due to ```f.rc.Close()``` in ftpReadCloser.Close() being stuck for unknown reasons. 

I didn't see anything weird in https://github.com/jlaffaye/ftp/blob/427467931c6fbc25acba4537c9d3cbc40cfa569b/ftp.go#L576 that could cause a wait.

I'm new to golang (first day :)) does a lot of lock on a lot of goroutine cause the whole thread to be waiting or just the goroutine ? Logic of golang would be just the goroutine.

**Comment by Speedy37** [comment]
I just did a quick test without this pull request changes, and a get the same lock, caused by: https://github.com/jlaffaye/ftp/blob/427467931c6fbc25acba4537c9d3cbc40cfa569b/ftp.go#L581

**Comment by Speedy37** [comment]
jlaffaye/ftp#117

**Comment by ncw** [comment]
I don't really want to add another flag to control concurrency when we have `--checkers` and `--transfers` already.

What we could do is make the number of tokens available be `fs.Config.Transfers` + `fs.Config.Checkers` - that would be fine and would avoid adding another concurrency control flag to rclone.

Note that the actual concurrency control would be much better done with the [TokenDispenser](https://github.com/ncw/rclone/blob/master/lib/pacer/tokens.go#L11).  Your use of `sync.Cond` is very clever.  However it is much more go style to use a channel for this and rclone has an internal library which does it already.

Can you re-work the PR like that?

**Comment by Speedy37** [comment]
I'll revert back to unlimited pool size and move the limitation to use the TokenDispenser.

**Comment by ncw** [comment]
@Speedy37 did you want to fix this up?

**Comment by ncw** [comment]
@Speedy37 I'm going to close this now since I haven't heard from you, but if you'd like to resubmit with the new backend config system (where I'm less worried about lots of backend flags) I'll merge it - thanks :-)

**Comment by Speedy37** [comment]
Sure close it, I've found a way to limit it (can't go lower than 2 connections) and I had to give up one connection to stay stable (at some points a connection is pending close, while a new one is connecting I think).
And my provider (OVH backup) limits me to 3...

By the way, here is my current configuration:
```
export RCLONE_CHECKERS=1
export RCLONE_TRANSFERS=1
restic -o rclone.connections=2
```

**Comment by ncw** [comment]
OK great - glad you've found a work-around :-)

**Pull request closed without merging**
