### PR TITLE
vendor: update github.com/spf13/cobra

### PR DESCRIPTION
**Pull request by bmwiedemann**
- [ ] I have read the [contribution guidelines](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

To get the new zsh completion generator

as an alternative to PR #3289

### CODE REVIEW

**Comment by ncw** [comment]
It looks like you updated *everything* not just cobra?  Is that correct?

**Comment by bmwiedemann** [comment]
I followed the documentation and did
```bash
GO111MODULE=on go get -u github.com/spf13/cobra
GO111MODULE=on go mod vendor
git add $AllUntrackedFiles
git commit -a
```

I dont know go, so I was assuming that these were pulled in as dependencies.

**Comment by bmwiedemann** [comment]
tests fail from `go-md2man` and `github.com/russross/blackfriday v2.0.0+incompatible` being indeed incompatible.

**Comment by ncw** [comment]
> I followed the documentation and did
> 
> ```shell
> GO111MODULE=on go get -u github.com/spf13/cobra
> GO111MODULE=on go mod vendor
> git add $AllUntrackedFiles
> git commit -a
> ```
> 
> I dont know go, so I was assuming that these were pulled in as dependencies.

I guess cobra pulled in a huge number of dependencies

> tests fail from `go-md2man` and `github.com/russross/blackfriday v2.0.0+incompatible` being indeed incompatible.

I know how to fix that but since this has pulled in so many dependencies what I'm going to do is do a complete update of all rclone's dependencies including cobra which is something I normally do about this point in the release cycle.

I've done that in d61ba7ef78966b0903b623d18d258fbba923f712 - can you check that brought in the features that you wanted from cobra?

**Comment by bmwiedemann** [comment]
I verified that commit d61ba7e  did indeed help. Thanks.

**Comment by ncw** [comment]
Thanks for testing :-)

**Pull request closed without merging**
