### PR TITLE
added files-only and dirs-only to lsjson

### LINKED ISSUE #3090: Add dirs-only flag to lsjson
#### What is your current rclone version (output from `rclone version`)?

rclone v1.46

#### What problem are you are trying to solve?

Filter only directories in "lsjson" output

#### How do you think rclone should be changed to solve that?

add a flag "--dirs-only" to lsjson

### PR DESCRIPTION
**Pull request by calisro**
#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by calisro** [comment]
I've added files-only and dirs-only flags to lsjson and modifed lsf to use the lsjson updates.

**Comment by ncw** [comment]
Sorry for the delay in responding I've been on vacation.

If you run

```
go fmt cmd/lsf/lsf.go
go fmt fs/operations/lsjson.go
```

And add the changes to the commit, then push the build should pass.

I'm not 100% sure what is wrong with GolangCI yet - but the travis build doesn't the same tests in a less user friendly way so if that passes I'm happy.

**Comment by ncw** [comment]
I pushed those whitespace fixes for you as I want to merge this before the v1.47 release.  Hopefully all will go green and I'll merge :-)

**Comment by ncw** [comment]
That all looks good - will merge now :-)

**Pull request merged**
