### PR TITLE
password prompt in log unix #2220

### PR DESCRIPTION
**Pull request by qaskai**
I've came up with a fix for unix systems. On Windows the behaviour should remain the same, that is the prompt will still be going to Stderr.

### CODE REVIEW

**Comment by ncw** [comment]
That is a nice solution - well done :-)

I think it may be possible to do the Windows side with [DupliateHandle](https://msdn.microsoft.com/en-gb/library/windows/desktop/ms724251(v=vs.85).aspx) if you fancy having a go?

**Comment by qaskai** [comment]
Yeah, I'll give it a try.

**Comment by qaskai** [comment]
@ncw I've just run rclone on Windows and the problem doesn't seem to exist there - when the program is run with --log-file, password prompt appears in the terminal (and is not added to the log file) - which most probably means it goes to Stderr. Maybe someone well versed with Windows internals will be able to explain this behavior (not me unfortunately :) ).
Regardless, it seems that the issue existed only on Unix systems, so I think it is globally fixed now.

**Comment by ncw** [comment]
@qaskai Hooray!  Thanks for testing :-)

**Pull request merged**
