### PR TITLE
Updated version in snapcraft.yaml to say current from master branch

### PR DESCRIPTION
**Pull request by Dedsec1**
so i updated the snapcraft.yaml to say latest from master branch so we dont have to change the version number each time. plus someone could easily just do rclone --v or rclone -V to get the version anyway. launchpad is setup to auto git pull every hour or so to check for the latest changes that you made. 

https://github.com/Dedsec1/rclone/commit/e33aee919014b21d57d86da46c00b19222213c62

### CODE REVIEW

**Comment by ncw** [comment]
I can't merge this as it stands. What you need to do is reset your master branch back to origin/master, then make a feature branch with this change it.

I'd really like it to pull the current stable version, so it should use the git tag of that version number.

And we should make a separate rclone-dev to install the development version.

Is that possible?

**Comment by Dedsec1** [comment]
yes it should be possible, i will check with the snap team and see if its possible

**Comment by Dedsec1** [comment]
so it is possible,  just have to add two lines and test from my end, then we should be good to go

**Comment by Dedsec1** [comment]
setting up dev build now on launchpad so i can test everything before pushing out to the main repo.

**Comment by ncw** [comment]
I'm going to close this PR now as I think I've merged the changes from the other one.

To make my life easier, can you reset your master branch to match rclones, then branch to make new feature branches.

The problem is that your master has diverged from rclone's master so whenever you send a PR you send all the history from the change and the new commit.

Otherwise I have to cherry-pick your commits is a bit time consuming and error prone.

Thanks

**Comment by Dedsec1** [comment]
will do

**Pull request closed without merging**
