### PR TITLE
Display individual file transfer progress

### PR DESCRIPTION
**Pull request by klauspost**
Improve progress printing by displaying individual file progress, as well
as a moving average speed with ETA. Example output:

```
2015/09/15 16:38:21
Transferred:    183599104 Bytes (4646.49 kByte/s)
Errors:                 0
Checks:                 1
Transferred:            0
Elapsed time:       38.5s
Transferring:
 * 01_06_14.mp3: 33% done. avg: 1280.5, cur: 1288.8 kByte/s. ETA: 1m12s
 * 01_12_15.mp3: 33% done. avg: 1002.2, cur:  943.4 kByte/s. ETA: 1m17s
 * 01_13_14.mp3: 48% done. avg: 1456.8, cur: 1425.2 kByte/s. ETA: 39s
 * 01_19_15.mp3: 28% done. avg: 1226.9, cur: 1114.4 kByte/s. ETA: 1m37s
```

### CODE REVIEW

**Comment by ncw** [comment]
Nice feature - very cool!

I didn't like the rather intrusive changes in the operations.go code so I had a go at reworking them in the individual-file-progress branch. See 1a48633cd2e2bc595d6a0d1d31d605ddefccb143

What do you think?  Want to improve some more on that?

I changed the printout to only print the last 25 runes of file names, but I'm not sure that is perfect either!

Feel free to push any changes to that branch.

Thanks

Nick

**Comment by klauspost** [comment]
Very nicely done. Much less intrusive indeed!

**Comment by klauspost** [comment]
Sorry about not being able to continue work on your branch. Git was being very uncooperative.

I have added async updates to the current transfer speed. It was not being updated when transfer stalled, and the values for that were not properly weighed, so speed was usually higher than they should be.

**Comment by ncw** [comment]
I've merged that - thank you very much!

**Pull request closed without merging**
