### PR TITLE
drive: fix chunked upload

### PR DESCRIPTION
**Pull request by B4dM4n**
This fixes broken chunked uploads for Google Drive introduced by #2007

### CODE REVIEW

**Comment by ncw** [comment]
What were the symptoms of the breakage?  I tested a chunked upload and it worked fine, or at least I thought I did!

**Comment by B4dM4n** [comment]
I got
> ERROR : rand.bin: Failed to copy: json: cannot unmarshal object into Go struct field File.parents of type string

after all chunks got uploaded.

This happened because `json.NewDecoder(res.Body).Decode(&rx.ret)` tried to decode a v2 response into a v3 `*drive.File`, where `parents` is a list and not a string.

**Comment by ncw** [comment]
Well done for fixing it! And -1 to me for shoddy testing ;-)

**Comment by B4dM4n** [comment]
I can't believe that I didn't noticed this earlier. I tested the v3 API live, but not with uploads >8MB :see_no_evil:

**Pull request merged**
