### PR TITLE
SFTP remote: fix typos and clarify disable_hashcheck prompt

### PR DESCRIPTION
**Pull request by miguno**

### CODE REVIEW

**Comment by ncw** [comment]
That is great thanks!  Fancy updating the corresponding text in [the example in the sftp docs](https://github.com/ncw/rclone/blob/master/docs/content/sftp.md) too?

**Comment by miguno** [comment]
Updated @ncw.

FWIW, it does confuse me that, in rclone, you have to set an option like `disable_hashcheck` to a blank value to enable it.  I would have expected that it would need to be set to `true` or sth similar, and that leaving the setting blank would mean the default value would be used (which I would have assumed to be `false` here, i.e. the hash check would be enabled).

That's also why I am not 100% sure that the updated sftp example text makes sense. :)

**Comment by ncw** [comment]
> FWIW, it does confuse me that, in rclone, you have to set an option like disable_hashcheck to a blank value to enable it. I would have expected that it would need to be set to true or sth similar, and that leaving the setting blank would mean the default value would be used (which I would have assumed to be false here, i.e. the hash check would be enabled).

`disable_hashcheck` is a boolean value so empty string, `false` and `0` are all false, whereas `true` and `1` are true.

So I think leaving the entry blank will mean `disable_hashcheck` == `false` which will mean hash checks are enabled.

Does that make sense?

Maybe `leave blank to disable unless you know what you are doing.` isn't clear enough.  Leaving it blank disables the option which enables the hashes.

How about something like `leave blank to enable hashing (recommended) set to true to disable hashing.`

**Comment by ncw** [comment]
Thank you very much for that - much appreciated!

**Pull request merged**
