### PR TITLE
Fix move and copy from TeamDrive to GDrive

### PR DESCRIPTION
**Pull request by fionera**
#### What is the purpose of this change?
When trying to copy or move between a TeamDrive and normal GDrive the SupportsTeamDrive flag will not be set since the destination isnt aware of the Source

#### Was the change discussed in an issue or in the forum before?
Nope
#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by desimaniac** [comment]
Confirmed this is working.

**Comment by EnorMOZ** [comment]
Any chance getting this into the next beta ?

**Comment by ncw** [comment]
I rebased this to see if we can get the tests passing...

**Comment by EnorMOZ** [comment]
Maybe add the https://github.com/ncw/rclone/issues/3119 stuff in this PR as well ?

**Comment by ncw** [comment]
Attempt #2 at rebasing!

**Comment by ncw** [comment]
This is looking good - will merge now - thank you :-)

**Pull request merged**
