### PR TITLE
drive: add new command 'about' to get quota info from a remote

### PR DESCRIPTION
**Pull request by a-roussos**
I have tried to implement a new rclone command called `about` that fetches quota information from a remote (it only works with Google Drive at the moment). My main motivation behind this was a colleague of mine who requested this feature; other users have expressed a similar interest in #1138 and #1564.

The command output looks like this:

```
$ rclone about gdrive:
Quota: 15 GiB | Used: 5.6 GiB (Trash: 0.0 GiB) | Available: 9.4 GiB | Usage: 37%
Space used in other Google services (such as Gmail): 0.05 GiB
```

With no previous knowledge of Go programming I relied on reading up earlier pull requests and their corresponding commits to get an idea about how such a feature could be added to rclone. As such, my attempt is probably a bit amateurish so please forgive any mistakes you may spot. Having said that, I _did_ try to follow the 'Contributing to rclone' document and actually ran the unit tests for the remote I modified (there were a few SKIPs but the rest PASSed).

One thing that's unclear to me is whether I need to add a file under `docs/content/commands` for the `about` command. The existing files contain the line `Auto generated by spf13/cobra` so I guess there's a script that creates them automatically?

### CODE REVIEW

**Comment by a-roussos** [comment]
It looks like I can only get the Travis CI build to succeed partially (apparently, [some build jobs](https://travis-ci.org/ncw/rclone/jobs/340368645) are failing due to `golint` errors). Apologies for not spotting these earlier: my system's (Debian 9) Go version is too old (1.7.4), so the source quality checks were skipped when I ran `make check`. I'll try to install the 1.9.4 release from golang.org and try again.

**Comment by ncw** [comment]
> One thing that's unclear to me is whether I need to add a file under docs/content/commands for the about command. The existing files contain the line Auto generated by spf13/cobra so I guess there's a script that creates them automatically?

You don't - these are automatically generated by `make commanddocs` and I don't generally update them  except during the release.

I've looked at the code you've done and it looks very good :-)

I have some comments I'll write here
  * there needs to be a pass-through implementation for `crypt` too.
  * The about interface should either take an `io.Writer` or return a string (see below for some other ideas)
  * note there is `rclone cachestats` which could potentially be folded into `about`

What do you think of taking the level of abstraction up a little?  Rather than just getting the `About()` methods to print things, return some more structured info.

You can be sure that the next request will be to return things in machine readable format!  I can see a `--json` flag request  ;-)

Looking at https://github.com/ncw/rclone/issues/1564#issuecomment-318887660 I had the idea that this should be returning a struct with a superset of all possible info.

So something like this, which returns the specific info, but also has room for extra stuff.  The `about` command can then print this in a sensibly formatted way (I'd suggest reasonably machine parse-able). Having an About command which returns machine readable data would mean that for instance `sync` could use it to check the data would fit and `rclone mount` could use it to return a sensible bytes free and available`.

```go 
type Usage struct {
	Total   int64                  // quota of bytes that can be used
	Used    int64                  // bytes in use
	Trashed int64                  // bytes in trash
	Other   int64                  // other usage eg gmail in drive
	Free    int64                  // bytes which can be uploaded before reaching the quota
	Text    []string               // lines of freeform text to show the user
	Values  map[string]interface{} // extra data that doesn't fit into the above
}
```

Note that you can print those `int64` by casting them to a `fs.SizeInfo` and they will print neatly.

That would make the `Abouter` interface `About() (*Usage, err)`

Thoughts?

**Comment by a-roussos** [comment]
> I've looked at the code you've done and it looks very good :-)

Thank you for your feedback. I was merely mimicking `CleanUp()` and copying/pasting code here and there ;-)

> Thoughts?

I agree that `About()` should return some more structured info instead of just printing strings. Your idea of other parts of rclone using the data from the struct for their own purposes is also very cool -- I hadn't thought about that.

However, having battled with this on and off over the last few days I've made very little progress. For the most part I've been reading up on Go programming principles (things like the Go Bootcamp book, gobyexample.com, etc.) and also perusing the rclone source code to get an idea about how to implement a function that does what you suggested.

It looks like the next step is a bit more complicated; I'm determined to pursue this further but I think it's going to require a fair amount of hand-holding...

For example, my questions at this stage are:
1) What is meant by "_pass-through implementation_" in a Go (or even rclone) context?
2) I've changed the `Abouter` interface to `About() (*Usage, err)` in `fs/fs.go` and also added the `Usage` struct definition in the same file. I've also modified the `About()` function signatures and corresponding return statements in `backend/cache/cache.go`, `backend/drive/drive.go` and `fs/operations/operations.go`.
Building the project now yields the following message: `# github.com/ncw/rclone/cmd/about | src/github.com/ncw/rclone/cmd/about/about.go:24:4: too many arguments to return | have (*fs.Usage, error) | want (error)`
Looking at the other `cmd.Run()` calls in `cmd/<command>/<command>.go` they all have a fourth argument of `func() error`, so how to fix this?

**Comment by ncw** [comment]
> It looks like the next step is a bit more complicated; I'm determined to pursue this further

Great!

> What is meant by "pass-through implementation" in a Go (or even rclone) context?

The `crypt` and `cache` backends wrap other remotes.  This means you need to pass through the About call to the wrapped remote.

It would end up being quite simple probably, just something like this

```go
// About returns info about a remote
func (f *Fs) About() (*fs.About, err) {
	return f.Fs.About()
}
```
Actually reading the code again, you don't need to so that.  Because the wrapped `Fs` is [embedded](https://golang.org/doc/effective_go.html#embedding) in `crypt.Fs` its `About` method will be visible directly.

> Building the project now yields the following message: # github.com/ncw/rclone/cmd/about | src/github.com/ncw/rclone/cmd/about/about.go:24:4: too many arguments to return | have (*fs.Usage, error) | want (error). Looking at the other cmd.Run() calls in cmd/<command>/<command>.go they all have a fourth argument of func() error, so how to fix this?

Not sure I understand exactly what is happening without seeing the code.  Remember you now need to print what is in the *About in the `cmd/about/about.go` - I expect you are trying to return it...

**Comment by ncw** [comment]
@a-roussos I see you haven't had time to work on this recently - would you like me to finish off this pull request?

In the mean time I've rebased it and stuck it in the `about` branch

Here is a beta based off it

https://beta.rclone.org/v1.40-085-g76dd198d-about/ (uploaded in 15-30 mins)

**Comment by turly** [comment]
I just tried Nick's beta on Ubuntu X86-64.
I have an unlimited gdrive and get some rather odd looking output so maybe a bit of sanity checking is needed.  (For all I know it's google themselves returning these numbers.)
```
Quota: 0 GiB | Used: 7920.3 GiB (Trash: 0.0 GiB) | Available: -7920.3 GiB | Usage: -9223372036854775808%
Space used in other Google services (such as Gmail): 0.00 GiB
```

**Comment by i336** [comment]
This looks really really good. For reference, I came here from https://forum.rclone.org/t/feature-request-cloud-storage-quota-querying/5393.

```
$ ./rclone about asmqb7:
Quota: 15 GiB | Used: 6.0 GiB (Trash: 0.0 GiB) | Available: 9.0 GiB | Usage: 40%
Space used in other Google services (such as Gmail): 0.74 GiB
```

I can immediately file a minor bug with this command however: forgetting the colon (which I may or may not have done the first time I tried the new command) breaks in fascinating ways.

```
$ ./rclone about asmqb7
2018/04/16 12:06:05 ERROR : Attempt 1/3 failed with 0 errors and: Local file system at /data/rclone-v1.40-085-g76dd198d-aboutβ-linux-386/asmqb7 doesn't support about
2018/04/16 12:06:05 ERROR : Attempt 2/3 failed with 0 errors and: Local file system at /data/rclone-v1.40-085-g76dd198d-aboutβ-linux-386/asmqb7 doesn't support about
2018/04/16 12:06:05 ERROR : Attempt 3/3 failed with 0 errors and: Local file system at /data/rclone-v1.40-085-g76dd198d-aboutβ-linux-386/asmqb7 doesn't support about
2018/04/16 12:06:05 Failed to about: Local file system at /data/rclone-v1.40-085-g76dd198d-aboutβ-linux-386/asmqb7 doesn't support about
```

My guess is that something's trying to assume the parameter is a local path.

Notwithstanding general heuristic error handling (something for the future), I'd probably handle this by bombing out and insisting on a colon rather than accepting no colon just for this command - unless someone can think of something `about` could do with local directories/files? Reporting something like "this is a local sync directory, it's such-and-such in sync with this remote" comes to mind, but the amount of implicit state and duct tape I'm imagining would be needed for such a feature does scare me off a little.

---

I can definitely +1 the idea of JSON reporting for this command. I could easily see myself using it.

---

@turly: My guess is that unlimited gdrive accounts return interesting JSON (a vague scan-over of the documentation recently suggested there may be no quota field (very nice)). It would be useful to get an unambiguous example of exactly what the JSON looks like in this case, and fetching it directly is actually quite straightforward thanks to Google's API explorer:

- Head over to https://developers.google.com/drive/v3/reference/about/get, and scroll down to the Try section

- Drop down "Show standard parameters", and put `storageQuota` in `fields` (the UI says "no method-level parameters", I'm unsure if this is a bug since this parameter is required)

- If you wish, you can drop down "Show scopes" and deselect all but `https://www.googleapis.com/auth/drive`, which is the only required scope for this API call

- When you hit Execute you'll get an OAuth popup, which may ask you which Google account to proceed with if you have more than one
 <sub>(NB. In some cases the OAuth flow doesn't provide a way to "go back" and switch accounts if you pick the wrong one. If you hit this edge case, the simplest solution (besides clearing cookies) is probably Incognito.)</sub>

- Let us see the JSON that gets returned - for example, mine looks like

```
{
 "storageQuota": {
  "limit": "18253611008",
  "usage": "771845240",
  "usageInDrive": "238462557",
  "usageInDriveTrash": "0"
 }
}
```

Which, for context, corresponds to 17GB quota, 736.1MB used total, 227.4MB used by Drive (and a tidy trashcan :P).

**Comment by ncw** [comment]
@turly - I have a very good idea of what is happening here!  I suspect it is signed vs unsigned 64 bit integers coerced to floating point doubles.  Anyway, can you run the command with `-vv --dump bodies` and paste the bit of JSON that @i336 suggests above which mentions `storageQuota`.

**Comment by turly** [comment]
Sorry, I should have thought of doing that:

```
77
{
 "storageQuota": {
  "usage": "8505366693932",
  "usageInDrive": "8505366693932",
  "usageInDriveTrash": "1628"
 }
}

0
```

**Comment by a-roussos** [comment]
Hi @ncw! Yes, if you could finish off this pull request it would be great. Thank you!

**Comment by ncw** [comment]
OK @a-roussos will do - thank you for starting the ball rolling :-)

**Comment by ncw** [comment]
I have merged this into the about branch.  I'm going to work on this there - this will produce betas with the `-about` tag on them.

For further updates see #1564

I'm going to close this PR - expect it to land in v1.41!

**Comment by ncw** [comment]
OK here is probably the final version of about before I merge it - comments appreciated!

https://beta.rclone.org/v1.40-089-gef3bcec7-about/ (uploaded in 15-30 mins)

See the docs here: https://github.com/ncw/rclone/blob/about/cmd/about/about.go#L44

This is supported for local, crypt, cache, drive, swift, hubic, onedrive, pcloud, dropbox

**Pull request closed without merging**
