### PR TITLE
Proposal for revising stats display.

### PR DESCRIPTION
**Pull request by klauspost**
Proposal for issue #379

Currently the revised output looks like this:

```
2016/03/12 13:52:25
Checked:           192593 of 46673217 bytes (0.41%) in 5 of 1172 files
Transferred:       176799 of 186888 bytes (3.22 kB/s) in 41 of 50 queued files
Elapsed time:       53.6s
```
## Things to fix before merge
- [ ] `func Check(fdst, fsrc Fs)` should also update stats.
- [ ] If a file exist on src, that doesn't on dst, it is not added to "checked". That breaks this method of displaying stats.
- [ ] Add file deletion information.
- [ ] Tests.

Of course we should also agree that this is the right direction.

### CODE REVIEW

**Comment by TheTrueTom** [comment]
Is this still a WIP? I would love to see something like that happening. It would make the output a lot more readable.

**Comment by djace** [comment]
+1, would love to see this integrated!

Additionally, I would also suggest to clear the screen before each time the stats are printed out, or at least add an option to do that.

**Comment by ncw** [comment]
Sorry @klauspost I have dropped the ball on this PR.  Are you still interested in doing this?  I think the proposed stats output looks great :-)

**Comment by klauspost** [comment]
Don't sweat it, I have not looked much at it either. Meanwhile there has been 7 thumbs up, which indicates that there is interest.

**Comment by tynor88** [comment]
Will this eventually be merged in? I like this suggestion 👍

**Comment by peterberbec** [comment]
This does look great. Any chance we could rip --info=progress2 from rsync? :)

**Comment by kk7ds** [comment]
Is this still live? I would definitely like to see this be available!

**Comment by timofonic** [comment]
Any news? This would be quite interesting to have :D

**Comment by timofonic** [comment]
Uhm. Nothing?

**Comment by ncw** [comment]
I have finally fixed this here:

https://beta.rclone.org/v1.42-104-g6390dec7/ (uploaded in 15-30 mins)

It does it by keeping a backlog (10,000 by default settable with --max-backlog) of files to upload.

I've also added --stats-one-line which mimics rsyncs --progress=info2.  (Actuall --progress support to come in #2347)

rclone no longer keeps all the files it is due to transfer in memory so I couldn't apply this pull request directly, but I think the overall effect will be very similar.

**Pull request closed without merging**
