### PR TITLE
Check if directory exists during s3 Mkdir

### PR DESCRIPTION
**Pull request by kazagistar**
### Problem 
Sync to S3 fails if you don't have permissions to create buckets, but the bucket you are syncing to already exists.

### Reason
Mkdir is always called on Sync, but fails due to an authorization error.

### Solution
If Mkdir fails due to an authorization error, check if the directory already exists. If it does, don't error.

Checking if it exists before trying to create would be a performance regression so this seemed like a more optimal solution.

### CODE REVIEW

**Comment by ncw** [comment]
I recently did something very similar for swift - thanks! See c3a0c0c45198bad7e8fbfb191cf8c3527f41e7bb

I chose in the end to do the directory exists check first, and then if it fails attempt to create the bucket.

My reasoning for doing that was that creating the bucket isn't particularly common - you almost always copy to an existing bucket so the number of remote operations will be the same in the common case.

As for S3 that particular bit of code you've changed has been troublesome with the S3 look-alikes not producing exactly the correct error code (eg CEPH and Blackperl DS3) so changing it to check first would help there!

So what do you think about re-arranging slightly to
  * check bucket exists
  * create if didn't exist
  * return error if create failed for any reason

Also is it possible to be a bit sharper on the error code that `dirExists` is checking for?  At the moment any error will cause the bucket to be shown to not exist.  It should really be checking for a specific error and returning a flag, and an error I think.

Thanks

Nick

**Comment by kazagistar** [comment]
I'm still fairly inexperienced in Go, so thanks for the feedback. All the requested changes seem reasonable to me, so I'll see what I can do.

On the issue of [EAFP](https://docs.python.org/2/glossary.html#term-eafp) (easier to ask forgiveness then permission) vs [LBYL](https://docs.python.org/2/glossary.html#term-lbyl) (look before you leap)... I went with EAFP because the only case in which it was slower is the broken one, which clearly therefore had no users until this fix goes out; I was trying to prevent regressions for any existing users. However, I will gladly switch to LBYL, because, hey, that is my use case, so its better for me that way.

**Comment by ncw** [comment]
I think you want something like this for dirExists.  If it returns an error then you should report that.  If it doesn't then the bucket was either found or not found.

```go
// Check if the bucket exists
func (f *Fs) dirExists() (bool, error) {
	req := s3.HeadBucketInput{
		Bucket: &f.bucket,
	}
	_, err := f.c.HeadBucket(&req)
	if err == nil {
		return true, nil
	}
	if err, ok := err.(awserr.RequestFailure); ok {
		if err.StatusCode() == http.StatusNotFound {
			return false, nil
		}
	}
	return false, err
}
```

**Comment by kazagistar** [comment]
I'm sorry, I am not really sure how to read those CI results. What did I do wrong?

**Comment by ncw** [comment]
One test has started failing - I don't know why yet - it isn't your fault!  I'll fix it shortly.

**Comment by ncw** [comment]
I've fixed the failing test - if you rebase the branch then force push it should pass!

**Comment by kazagistar** [comment]
Ok. Anything else needed to push this upstream?

**Comment by ncw** [comment]
I've merged that in 694d390710a14304750897c5282d5b1f324a9559 (after rebasing and squashing the commits).

Thank you very much for your contribution

**Pull request closed without merging**
