### PR TITLE
Implemented PublicLink support for Jottacloud

### PR DESCRIPTION
**Pull request by albertony**
Title basically says it all..
Did not see any functionality in rclone for removing the public link again? That would be simple to implement for Jottacloud (just set mode "disableShare" instead of "enableShare")..

### CODE REVIEW

**Comment by albertony** [comment]
Squashed commits

**Comment by ncw** [comment]
Code looks great - thank you.

Can you rebase this on master please which will remove the conflict.

And if you haven't already can you check the integration test works

    cd backend/jottacloud
    go test -v

Thank you :-)

**Comment by albertony** [comment]
Now... (Hope I did it correct, as I'm not that experienced with Git)

**Comment by ncw** [comment]
I'm not super keen on the `--jottacloud-unlink` flag, but I'm going to merge as-is since I can't think of anything better :-)

Thank you for this - very useful.

**Comment by albertony** [comment]
I can agree with that. unlink as separate command would probably be cleanest, but overkill if only one or very few backends support it..

**Pull request merged**
