### PR TITLE
Fix tests failing on Windows.

### LINKED ISSUE #161: local: Fix characters allowed in filenames on windows
The current list of characters not allowed on windows are these - see [local.go cleanUtf8](https://github.com/ncw/rclone/blob/master/local/local.go#L179)

    '<', '>', '"', '|', '?', '*', '&'

However this doesn't quite agree with the [ms official documentation](https://msdn.microsoft.com/en-us/library/aa365247)

Which does allow '&' in file names and doesn't allow ':'.

### PR DESCRIPTION
**Pull request by klauspost**
+ ":" is kept when part of a drive.
+ "&" is removed, since it doesn't appear to work (at least on dev computer).
+ Create tests.

Fixes #161 and reverts #162

### CODE REVIEW

**Comment by klauspost** [comment]
More info. "&" doesn't appear to work on Windows. The "local" tests fail if there is a "&" in the file name. I have not digged deeper into why.

I made the Windows replacements a separate function so it was easier to test.

**Comment by ncw** [comment]
Sorry for the delay reviewing this!

This was the major reason for the tests failing with `&` in.  So I've fixed that in your commit and removed the escaping of `&` and tested that the local tests work on windows!

```diff
--- a/fstest/fstests/fstests.go
+++ b/fstest/fstests/fstests.go
@@ -36,7 +36,7 @@ var (
        file2 = fstest.Item{
                ModTime: fstest.Time("2001-02-03T04:05:10.123123123Z"),
                Path:    `hello? sausage/êé/Hello, 世界/ " ' @ < > & ?/z.txt`,
-               WinPath: `hello_ sausage/êé/Hello, 世界/ _ ' @ _ _ _ _/z.txt`,
+               WinPath: `hello_ sausage/êé/Hello, 世界/ _ ' @ _ _ & _/z.txt`,
        }
 )
```

I pushed that to klauspost-windows-escaping branch for you to adjust futher if you want.

Thanks

Nick

**Comment by klauspost** [comment]
Looks perfect. Sorry for not thinking of that. Silly me.

**Comment by ncw** [comment]
I've merged that - thanks!

**Pull request closed without merging**
