### PR TITLE
New option (drive-auth-owner-only) to only consider files owned by the authenticated user

### PR DESCRIPTION
**Pull request by bjornharrtell**
Implements #255.

Note that it will only work with full listing (documented in the option)

Disclaimer: My first ever lines of Go. :)

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Just now noted that unit tests are required + squash to single commit. Will try to get that done ASAP. Until then I would appreciate prel. review.

**Comment by bjornharrtell** [comment]
Squashed. Not sure I can make unit tests... would need to share item from other user to get an not-owned item.

**Comment by ncw** [comment]
That looks very nice - well done! One minor thing commented inline.

Can you add a bit for the docs too please - in the specific options section in `docs/content/drive.md`.

Thanks

Nick

**Comment by bjornharrtell** [comment]
Thanks! Fixed the docs issues.

**Comment by ncw** [comment]
I have merged this - thank you very much for the contribution.

**Pull request closed without merging**
