### PR TITLE
created rclone-dev snapcraft.yaml

### PR DESCRIPTION
**Pull request by Dedsec1**
here is the rclone-dev snapcraft.yaml file within its own branch so its easier to manage dev builds

### CODE REVIEW

**Comment by ncw** [comment]
don't we need a new section in the existing snapcraft file (or maybe a new file) so it builds both the release rclone and the dev one?

**Comment by Dedsec1** [comment]
thats what i did, i created another file on an new branch and pointed launchpad to use the dev snapcraft file instead of the stable release one on the master branch.

**Comment by ncw** [comment]
> thats what i did, i created another file on an new branch and pointed launchpad to use the dev snapcraft file instead of the stable release one on the master branch.

That doesn't really fit in with rclone's workflow though - maintaining a second branch would be a lot of work.

What about a new section in the existing snapcraft file to make the rclone-dev?  or a snapcraft-dev.yml file?

**Comment by Dedsec1** [comment]
gotcha, i will move the file into the master branch and do an PR

**Comment by ncw** [comment]
I've merged that now.  I called the new file snapcraft-dev.yaml though - I try not to put file names with spaces in source code repositories.

**Pull request closed without merging**
