### PR TITLE
cmd: added retries-sleep flag

### LINKED ISSUE #2339: [Feature Request] Sleep before retrying
#### What is the problem you are having with rclone?
This is a problem with plexdrive crashing but nonetheless I also wanted a delay for rclone's retries to allow the whatever backend being used to reconnect before retrying the transfer.

A sleep-before-retry <time> parameter would be nice.
e.g:
```sh
$ rclone copy --sleep-before-retry 3s source destination
```

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.41
- os/arch: linux/amd64
- go version: go1.10

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 18.04 / 64-bits

####  Which cloud storage system are you using? (eg Google Drive)
Plexdrive mount backend for a crypted drive to avoid being account banned/file download quota limit
drive = /mnt/plexdrive/crypted-drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy -vv --stats 30s --retries 15 --low-level-retries 10 --exclude-from exclude.txt drive: /mnt/pool/

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
[excerpt.log](https://github.com/ncw/rclone/files/2075255/excerpt.log)

### PR DESCRIPTION
**Pull request by bjdag1234**
this fixes #2339 

It is a simple addition to the Run command, upon testing it works for my use case as specified in the issue. while this is a simple code, I don't know if it works for other use cases  and if some other bugs sprout from the addition of this.

### CODE REVIEW

**Comment by ncw** [comment]
The code looks good :-)  Can you run it through `gofmt` and push it again to make the CI pass?  Thanks

**Comment by bjdag1234** [comment]
it seems that it keeps failing the CI builds, is there anything i should do to fix this?

**Comment by ncw** [comment]
It doesn't look like your code, it looks like something is up with github or travis... I've retried it.

**Comment by ncw** [comment]
I've merged this now - thank you very much for your contribution :-)

**Pull request merged**
