### PR TITLE
Initial docs for usage with DigitalOcean Spaces.

### PR DESCRIPTION
**Pull request by andrewsomething**
An initial crack at docs for basic configuration and usage of DigitalOcean Spaces. See: #1750

### CODE REVIEW

**Comment by andrewsomething** [comment]
Tested locally with `make serve` the build failure seems unrelated.

**Comment by ncw** [comment]
That is very nice thank you.  I'm going to hold off on merging it just for the moment until we've decided on exactly what the config should be for digital ocean spaces.

**Comment by ncw** [comment]
There is something a little funky with the regions going on, but after a little testing I think leaving it blank is the best option.

So if you could update your PR to produce a config which looks like this then I'll merge it.

So that is just press enter on the region.  That produces a v4 auth config which works fine in my testing.

```
[do2]
type = s3
env_auth = false
access_key_id = XXX
secret_access_key = XXX
region = 
endpoint = nyc3.digitaloceanspaces.com
location_constraint = 
acl = 
server_side_encryption = 
storage_class = 
```

Thanks

Nick

**Comment by andrewsomething** [comment]
Great! Updated and commits squashed.

**Comment by ncw** [comment]
Perfect thanks!

**Pull request merged**
