### PR TITLE
azureblob and fstests - Exclude archive tier from SetTier integration tests

### PR DESCRIPTION
**Pull request by sandeepkru**
azureblob and fstests - Exclude archive tier from SetTier integration tests, added ExcludedSettings to fstests.Opt, a key-value map to hold various settings, where key is setting name and value is list of settings

### CODE REVIEW

**Comment by sandeepkru** [comment]
@ncw - I settled on below approach, please let me know if you have any concerns, I can change this is to be an option of simple slice of strings, but I thought this would be more generic and can be used in different purposes.
```console
	// Describes map of key value pair settings, key is setting name and value is
	// list of settings as strings which can be excluded from tests
	ExcludedSettings map[string][]string
```

**Comment by ncw** [comment]
I think I prefer the less generic approach of

```golang
    TiersToTest []string
```

That has the advantage that it is fully typed and we can use the compiler/go-oracle to find uses.

The test should break if the interfaces are found but `TiersToTest` is empty.

**Comment by sandeepkru** [comment]
Sounds good, with this `ListTiers` not used anywhere hence I removed that code as well. It can be introduced with `S3 and GCS` changes at `Fs` level correctly.

**Comment by ncw** [comment]
That looks great now - thank you :-)

I'll merge it now.

**Pull request merged**
