### PR TITLE
Add support to toggle bandwidth limits via SIGUSR2.

### PR DESCRIPTION
**Pull request by marcopaganini**
Sending rclone a SIGUSR2 signal will toggle the limiter between off and
the limit set with the --bwlimit command-line option.

### CODE REVIEW

**Comment by ncw** [comment]
Thanks for thinking about this and apologies for not replying sooner.  Changing the bwlimit dynamically is a popular feature request for rclone.

Signals as a method for controlling it are problematic though as they don't work on Windows (& Plan 9) as the failed appveyor build shows.

    fs\accounting.go:47: undefined: syscall.SIGUSR2

Now this could be fixed with a few [build tags](https://golang.org/pkg/go/build/#hdr-Build_Constraints) (nice [blog about conditional compilation](http://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool))

However what would you think about implementing #221 instead which would vary bwlimit by time of day?  that would fix the problem for most people and be cross platform portable? Would that satisfy your use case?

**Comment by marcopaganini** [comment]
Aha! That's why appveyor was failing then! I was curious about that. Looking at the logs, it didn't appear to be anything related to my changes, and I was puzzled.

What about adding conditional compilation *and* time of day for this feature? I could try fixing this issue and implementing #221.

I think it's also important to have a "tactical" way to turn bwlimit on and off. Would you have any suggestions on portable ways to do this? Being a Unix/Linux guy, I don't know what methods are available to Windows (signals are clearly a problem). Any ideas?

**Comment by ncw** [comment]
> Aha! That's why appveyor was failing then! I was curious about that. Looking at the logs, it didn't appear to be anything related to my changes, and I was puzzled.

It originally blew up with something random like a timeout fetching something, but I re-ran the build today so your confusion is understandable!

> What about adding conditional compilation and time of day for this feature? I could try fixing this issue and implementing #221.

If you want to do that, then that would be fine.  I suggest you make this PR work for the conditional compilation needed then do a separate one for #221

> I think it's also important to have a "tactical" way to turn bwlimit on and off. Would you have any suggestions on portable ways to do this? Being a Unix/Linux guy, I don't know what methods are available to Windows (signals are clearly a problem). Any ideas?

I have to admit to not really being a windows dev either though I have done some windows dev stuff in the past (with win32 api!).

Doing IPC opens a whole can of worms in the general case...  Probably the easiest way would be for rclone to listen on a localhost:socket for commands if you supply a `--rpc host:port` parameter then make a separate rclone command `rclone rpc bwlimit 10k` to interact with the running rclone.  There are some security implications doing it like that, so a named pipe might be better.

I suggest you just ignore windows for the time being - I want to solve the IPC thing in a general way for tickets like #771 and some other ideas I've got.

**Comment by marcopaganini** [comment]
Done. Conditional compilation is in place.

**Comment by ncw** [comment]
I've merged that in cc4f5ba7ba5bbebb31ad4f2f3c8d28e13613cc3f (after rebase).

After a bit of testing I realised that the build was broken for some builds, and the race detector warned me that the update of the token bucket was racey so I fixed those things in e65059e431642d497bc0b134270cd3032d87f790

Thank you very much for your contribution :-)

**Comment by DurvalMenezes** [comment]
Hello @ncw, @marcopaganini,

> Signals as a method for controlling it are problematic though as they don't work on Windows (& Plan 9) as the failed appveyor build shows.

Plan 9?! Wow, just noticed that rclone builds are routinely available for it. Say (if it's not too OOT), is Plan 9 ready for anything but a lab setting? Just curious here, been following it for a long time but never thought I would see it become usable. 

> > I think it's also important to have a "tactical" way to turn bwlimit on and off. Would you have any suggestions on portable ways to do this? Being a Unix/Linux guy, I don't know what methods are available to Windows (signals are clearly a problem). Any ideas?
> I have to admit to not really being a windows dev either though I have done some windows dev stuff in the past (with win32 api!).

I've developed with Windows too (a *long* time ago: Windows 3.1 and Win16 API, at the time called simply "the Windows API"). I still remember the horror... 

But anyway, I would like to make a suggestion: Windows (since the Win16 days) has supported an IPC mechanism called "named pipes". This is very similar to what we call FIFOs in *ix (and I would bet there's similar stuff in Plan 9), so perhaps this would be the best way to implement such a feature going forward? More info here: https://en.wikipedia.org/wiki/Named_pipe#In_Windows

Also, this would open up the door for more sophisticated "run-time behavior changing" for rclone; for example, I frequently need to restart rclone to change --transfers and --checkers; with a FIFO-like IPC between a standalone rclone (which would be called with the "--client=/tmp/pipe-filename" or somesuch) and the running rclone (which would have been started before, with a "--server=/tmp/pipe-filename option), basically anything could be piped up to the running rclone to have it change its behavior. 

Alternatively, one could use a socket in the same way; one program which does this is aria2 (see here: https://github.com/aria2/aria2/blob/master/doc/xmlrpc/aria2rpc but perhaps it's more complicated than warranted... 

Hope you folks like the idea and implement it soon ;-)

Cheers, 
-- 
   Durval.


Cheers,

**Comment by ncw** [comment]
@DurvalMenezes 

> Plan 9?! Wow, just noticed that rclone builds are routinely available for it. Say (if it's not too OOT), is Plan 9 ready for anything but a lab setting? Just curious here, been following it for a long time but never thought I would see it become usable.

Some of the core go developers use plan 9 or at least hack on it.  No idea how well it works though!  Go makes doing cross compilations really easy so I did it for plan 9 just because it was easy!

> But anyway, I would like to make a suggestion: Windows (since the Win16 days) has supported an IPC mechanism called "named pipes"

There are some ideas along the lines you suggested in #771

> Also, this would open up the door for more sophisticated "run-time behavior changing" for rclone; for example, I frequently need to restart rclone to change --transfers and --checkers

That is a nice idea... Fancy making an issue about it?

**Pull request closed without merging**
