### PR TITLE
Koofr backend: support for setting modification times

### PR DESCRIPTION
**Pull request by jkmcnk**
#### What is the purpose of this change?

Support for setting modification times on Koofr backend.

#### Was the change discussed in an issue or in the forum before?

No.

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [X] I have added tests for all changes in this PR if appropriate.
- [X] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by buengese** [comment]
Could you explain a bit more how this works? What if the user answers the setmtime option wrong? Could this be detected automatically?

**Comment by jkmcnk** [comment]
> Could you explain a bit more how this works? What if the user answers the setmtime option wrong? Could this be detected automatically?

for this to be relevant, the user must meddle with the advanced options in the first place, to select a location that goes to a dropbox or amazon drive backed storage, and not to a Koofr-hosted one, so I don't find this such a problem. tbh, it could be detected automatically, but would require some network communication with the server just to return from the Precision() method: thus, I opted to avoid this.

**Comment by buengese** [comment]
I see looks fine to be but I think we're gonna wait for ncw to return from vacation before merging this.

**Comment by jkmcnk** [comment]
> I see looks fine to me but I think we're gonna wait for ncw to return from vacation before merging this.

ofc. we're in no hurry, but hopefully we get this merged in prior to next release.

**Comment by ncw** [comment]
I think this looks sound to me.  Do the integration tests pass with and without the flag?

**Comment by jkmcnk** [comment]
> I think this looks sound to me. Do the integration tests pass with and without the flag?
yes. except for the obviously wrong case of declaring that the backend supports setting mtime while directing the files to a dropbox backend connected via koofr.

**Comment by ncw** [comment]
Great.  The code for this looks good - will merge now :-)

**Comment by ncw** [comment]
Thank you very much

**Pull request merged**
