### PR TITLE
Adds --user-server-modtime flag

### PR DESCRIPTION
**Pull request by ipmb**
I'm not much of a go programmer, but taking a crack at this one. I haven't added or run tests because I don't know how :)

refs #2199

### CODE REVIEW

**Comment by ncw** [comment]
The code is looking good now and the tests pass!

I think it woud be worth writing a generic paragraph about syncing with `--update` and `--use-server-modtime` and sticking it after the `--fast-list` paragraph in the [s3](https://github.com/ncw/rclone/blob/master/docs/content/s3.md#--fast-list) and the [swift](https://github.com/ncw/rclone/blob/master/docs/content/swift.md#--fast-list) docs.  Do you fancy having a go at that too?

**Comment by ipmb** [comment]
I'd be happy to, but I don't fully understand the `--update` flag.

> This forces rclone to skip any files which exist on the destination and have a modified time that is newer than the source file.

Is this for operations other than `sync`? For `sync`, I would expect this is the default.

> On remotes which don't support mod time directly the time checked will be the uploaded time.

I thought that was the functionality I just added. Does this do the same thing?

**Comment by ipmb** [comment]
Is there a flag I can use to see the API calls rclone is making?

**Comment by ipmb** [comment]
I think I get it now... lmk if a628e6cd3e09e66c4cf72bb2a9eb0eca237da0bf makes sense.

**Comment by ncw** [comment]
> Is there a flag I can use to see the API calls rclone is making?

Sure, use `-vv --dump bodies` to see the http transactions.  It will dump your file data too, so test with text files!  See the other `--dump` options for logging less.

**Comment by ncw** [comment]
> I think I get it now... lmk if a628e6c makes sense.

that looks very nice now - thanks.  Are you ready for me to merge this?

**Comment by ipmb** [comment]
Yep. Thanks! :shipit:

**Comment by ncw** [comment]
I've squashed and merged that now - sorry for the delay.

Thanks for a great piece of code - that will be very useful (especially to me since I use swift a lot!)

**Pull request merged**
